### ISSUE TITLE
Provide support for @RequestBody with a String as a raw JSON

### ISSUE THREAD

**Issue by dacofr** [ScaCap/spring-auto-restdocs#101]
Hi,

first thanks for your good work :)

I've this case
```
@RequestMapping(method = POST, value = "/bulk")
public ResponseBulkImport bulkImport(
	@RequestBody final String bulkImport)
{
	return service.doSomeWork(bulkImport);
}
```
I need to have the raw json to make some special controls so i can't use a bean.
But in my documentation, i want to explain all the fields my API can accept.

So in my test, it would be great if i could do something like that :

```
String bulkImport = new ObjectMapper().writeValueAsString(buildBulkImport());
mockMvc.perform(post("/classified/bulk")
		.with(documentRequestBodyAs(BulkImport.class))
		.contentType(APPLICATION_JSON_UTF8)
		.content(bulkImport))
```
Look at the documentBodyAs() method who is a RequestPostProcessor

I've found that i need to modify the **JacksonRequestFieldSnippet** classe and particulary the method  **Type getType(HandlerMethod method)**

But i don't know how to get the information  **BulkImport.class**

An other solution is to have something like that :
```
@RequestMapping(method = POST, value = "/bulk")
public ReponsesBulkImport bulkImport(
        @DocumentRequestBodyAs(BulkImport.class)
        @RequestBody final String bulkImport)
{
		return service.doSomeWork(bulkImport);
}
```
It's more easy to extract the information BulkImport.class, but i don't know 

- if  I a can use a standard annotation in Java
- use a Jackson annotation
- or write my own annotation but where to put it

It would be a pleasure to provide a PR, but i need some help to go in the good direction :)

Thanks

(sorry for my bad english)

**Comment by jmisur** [comment]
Hi thanks for the suggestions. Using `String` as request body is quite a corner case and we've yet to see what approach would cooperate with our extension. I would prefer the `documentRequestBodyAs` because that does not interfere with production code and could be similarly used in other cases.

**Comment by dacofr** [comment]
Hi,

i totaly agree with you to not interfere with production code.

To sole my problem, i've currently done in a  framework home-made

- Created an annotation
```java
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
public @interface AutoDocumentationOptions {
	Class<?> requestBody() default void.class;
}
```

- Reimplement your JacksonRequestFieldSnippet class
```java
public class InternalJacksonRequestFieldSnippet
	extends JacksonRequestFieldSnippet {
	private Type requestBodyType;

	InternalJacksonRequestFieldSnippet(Type requestBodyType) {
		super();
		this.requestBodyType = requestBodyType;
	}

	@Override
	protected Type getType(HandlerMethod method) {
		if ( requestBodyType != null ) {
			for (MethodParameter parameter : method.getMethodParameters()) {
				if ( isRequestBody(parameter) ) {
					return requestBodyType;
				}
			}
		}

		return super.getType(method);
	}

	private boolean isRequestBody(MethodParameter param) {
		return param.getParameterAnnotation(RequestBody.class) != null;
	}
}
```

- Create a rule to analyze my annotation AutoDocumentationOptions
```java
public class RuleAutoDocumentationOptions
	extends TestWatcher {
	private AutoDocumentationOptions options;

	@Override
	protected void starting(Description d) {
		options = d.getAnnotation(AutoDocumentationOptions.class);
	}

	Type getRequestBodyType() {
		return options != null ? options.requestBody() : null;
	}
}
```
- In my generic class for documenting controller, i've added my new rule and change your AutoDocumentation.requestFields() by my new InternalJacksonRequestFieldSnippet() 
```java
public abstract class AbstractControllerTestForDocumentation {
	@Rule
	public final JUnitRestDocumentation restDocumentation = new JUnitRestDocumentation(System.getProperties().getProperty("org.springframework.restdocs.outputDir"));

	@Rule
        // Using my internal Rule to analyse test method with my annotation
	public final RuleAutoDocumentationOptions options = new RuleAutoDocumentationOptions();

.. snip ...

	@Before
	public void setUp() throws Exception {
		this.mockMvc = MockMvcBuilders
			.webAppContextSetup(context)
			.alwaysDo(JacksonResultHandlers.prepareJackson(objectMapper))
			.alwaysDo(MockMvcRestDocumentation.document("{class-name}/{method-name}",
				Preprocessors.preprocessRequest(
					Preprocessors.prettyPrint()
				),
				Preprocessors.preprocessResponse(
					ResponseModifyingPreprocessors.replaceBinaryContent(),
					Preprocessors.prettyPrint())))
			.apply(MockMvcRestDocumentation.documentationConfiguration(restDocumentation)
				.uris()
				.withScheme(uriScheme)
				.withHost(uriHost)
				.withPort(uriPort)
				.and().snippets()
				.withDefaults(CliDocumentation.curlRequest(),
					HttpDocumentation.httpRequest(),
					HttpDocumentation.httpResponse(),
                                        // replace AutoDocumentation.requestFields() with my own implementation and provide with request body type to use
					new InternalJacksonRequestFieldSnippet(options.getRequestBodyType()), 
					AutoDocumentation.responseFields(),
					AutoDocumentation.pathParameters(),
					AutoDocumentation.requestParameters(),
					AutoDocumentation.description(),
					AutoDocumentation.methodAndPath(),
					AutoDocumentation.section()))
			.build();
	}

... snip ...
}
```

And now i my test i can write :

```java
@RunWith(SpringRunner.class)
@WebMvcTest(ImportExterneApi.class)
public class BulkImportDocumentationTest extends AbstractControllerTestForDocumentation {
... snip ...

	@Test
        // Using my annotation to specify which class to use to document request body
	@AutoDocumentationOptions(requestBody = BulkImport.class)
	public void bulkImport() {
              String rawJson="...";
              mockMvc
			.perform(post("/myendpoint")
			.contentType(APPLICATION_JSON_UTF8)
			.content(rawJson))
      }
... snip ...
}
```

Hope, if it could help you :)

**Comment by fbenz** [comment]
Thank you very much!

I was experimenting with an alternative solution that is closer to the usual Spring REST Docs style:
```java
                .andDo(document("{class-name}/{method-name}",
                        requestFields(ItemUpdateRequest.class)));
```
The type hint is directly provided to the snippet in the test itself. However, I found two disadvantages:
1. It cońflicts with a request field snippet that is configured as a default. It actually gets ignored because default snippets are prefered by Spring REST Docs (see `RestDocumentationGenerator.getSnippets`.
2. Our section snippets only works with default snippets. Changing that means that we have to extend Spring REST Docs a bit more, because `RestDocumentationGenerator` does not expose the list of snippets.

Both are quite annoying disadvantages.

Currently, I only see one disadvantage for your annotation approach:
1. A test could document several REST calls and then one has to think about ways to match the type hint to the right document call. However, I think that it's fine to tell users that this is not supported.

If in addition to the existing static factory method
```java
requestFiels()
```
the following static factory method
```java
requestFiels(options.getRequestBodyType())
```
would be offered, it would be backwards compatible and would give everybody the choice of using the type hint. One could even provide the type hint in a different way than via an annotation. But an annotation is a good solution to do so.

Therefore, we would be happy if you could submit a pull request.

**Comment by dacofr** [comment]
Hi @fbenz, thanks for your reply.

i will be happy to provide a PR :smiley:

I have lot of work on my current project before going in vacation :grimacing:,
but when i will be back from my holidays, it will be my first job to submit a PR

Thanks
