### ISSUE TITLE
Doesn't generate docs if the objects are in an external JAR

### ISSUE THREAD

**Issue by ganesh815** [ScaCap/spring-auto-restdocs#102]
The domain objects for our REST API is in an external library and is shared across our orchestration and domain micro services. Spring-auto-restdocs doesn't read the documentation from the external library (even if we include the source files).

**Comment by fbenz** [comment]
I have never tried to run a Javadoc doclet on a sources JAR. I tried to figure out how to do so, but found no instructions so far. If you figure this out, we would be glad to know the solution.

An alternative approach would be to run the doclet as part of the build of the external library (if possible) and package the resulting JSON files as resources of the JAR. This way one can copy the JSON files as part of the build of the REST API project into a folder and access them from there. It might also be possible to use them directly from the classpath.

**Comment by ganesh815** [comment]
This is exactly what we ended up doing. We generated the JSON file and included in the JAR. The client extracts the jar and copies the JSON files to its "generated-json-docs" directory. Thanks.

**Comment by dacofr** [comment]
Hi @ganesh815 ,
can you share your maven configuration file ? because i've the same problem.
Do you have create a new classifier Maven to store the generated JSON file or you do store it in the same jar of compiled classes ?

Thanks for your help

**Comment by jmisur** [comment]
@ganesh815 @dacofr could you try latest snapshot to see if it's working for you? It should now resolve json files from anywhere on the classpath.

**Comment by ganesh815** [comment]
@jmisur yes. I should be able to test today. Should I build from source or is the snapshot version published somewhere?

**Comment by jmisur** [comment]
unfortunately we do not publish snapshots anywhere, so please build from repo.

**Comment by jmisur** [comment]
Will be released in 1.0.9

**Comment by dacofr** [comment]
Hi,

sorry for my late response.
Resolving javadoc json file from the classpath, works fine.

Here is an extract of my maven configuration 

```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-javadoc-plugin</artifactId>
	<version>${version.maven-javadoc-plugin}</version>
	<executions>
		<execution>
			<id>generate-javadoc-json</id>
			<phase>compile</phase>
			<goals>
				<goal>javadoc</goal>
			</goals>
			<configuration>								<doclet>capital.scalable.restdocs.jsondoclet.ExtractDocumentationAsJsonDoclet</doclet>
				<docletArtifact>
					<groupId>capital.scalable</groupId>
					<artifactId>spring-auto-restdocs-json-doclet</artifactId>
					<version>${version.spring-auto-restdocs}</version>
				</docletArtifact>
							
				<additionalparam>-d "${project.build.outputDirectory}"</additionalparam>
				<reportOutputDirectory>${project.build.directory}</reportOutputDirectory>
				<useStandardDocletOptions>false</useStandardDocletOptions>
				<show>package</show>
			</configuration>
		</execution>
	</executions>
</plugin>
```

Note the **additionalparam** that permit to include in the same jar class files and json files with javadoc.

**Comment by fbenz** [comment]
@dacofr Thank you for reporting back and sharing your configuration.

**Comment by dacofr** [comment]
@fbenz No problem.

With this solution (embed json doc files directly inside the artifact), you must be backward compatible with old structure of JSON described in [ClassJavadoc](https://github.com/ScaCap/spring-auto-restdocs/blob/master/spring-auto-restdocs-core/src/main/java/capital/scalable/restdocs/javadoc/ClassJavadoc.java)

**Comment by fbenz** [comment]
@dacofr Got it and we just introduced a breaking change in the 1.0.10 release. It might be possible to make the next release backwards compatible. This would mean that 1.0.10 should be skipped in such cases. We will discuss it and see how much effort it is. We definitely have to be more careful in the future.

**Comment by m-titov** [comment]
https://github.com/ScaCap/spring-auto-restdocs/issues/102#issuecomment-341977902

Sorry, how to do the same in gradle?
And where javadoc json file should be inside lid jar?
