### ISSUE TITLE
How to manually add field description.

### ISSUE THREAD

**Issue by huangyg11** [ScaCap/spring-auto-restdocs#120]
Though request class and response is the same, the field description may be different. One example is create request. 

` POST /user`

the request `user` class don't need to provide a id field, and in the response `user` class, I need to document that the id is generated by the server.

How can I archive this?

**Comment by jmisur** [comment]
You have multiple options:
1) Provide field documentation in Javadoc and describe the behavior there.
2) Use different class for request and response - and in each of them only fields appropriate for the action. Use inheritance if it helps.
3) Provide validation annotations on the field, e.g.
```
@Null(groups = UserCreationGroup.class)
@NotNull(groups = UserResponseGroup.class)
private String id;
```
Even if you would not actually validate anything, documentation for constraints will be generated. In this case you can describe groups as documented [here](https://scacap.github.io/spring-auto-restdocs/#constraints-groups).
