### ISSUE TITLE
Failed to recognize pageable request param

### ISSUE THREAD

**Issue by huangyg11** [ScaCap/spring-auto-restdocs#121]
An endpoint that accept page and size parameter, but auto-restdocs failed to document it

```
    /**
     * index
     *
     * @param page page number
     * @param size size of a page
     */
    @GetMapping
    public Page<Video> index(Pageable pageable) {
        return videoRepository.findAll(QVideo.video.url.eq("http://a.com"), pageable);
    }

```
example request
```
curl 'http://localhost:8080/video?page=1&size=5' -i
```

**Comment by jmisur** [comment]
Whenever we discover `Page` response, we link to common "Paging support" section ([see example](https://github.com/ScaCap/spring-auto-restdocs/blob/master/spring-auto-restdocs-example/src/main/asciidoc/index.adoc#overview-pagination)). However that section does not distinguish query parameters from response. We'll improve that.
