### ISSUE TITLE
Do not pull hibernate validator transitively

### ISSUE THREAD

**Issue by filiphr** [ScaCap/spring-auto-restdocs#124]
I have a project where we actually do not use hibernate validator. The dependency is being pulled automatically by auto-restdocs which means that it is failing as I don't have implementation of the el-api in my dependencies.

I would propose that you make the hibernate-validator a provided dependency and only instantiate the `ConstraintReaderImpl` if hibernate is present, or even make it so that you can configure the `JacksonPreparingResultHandler`.

**Comment by filiphr** [comment]
@jmisur I think the fix won't solve the problem. If I have no constraint validation implementation this will fail again but with a different message.

Do you deploy snapshots? I can try it out in my project if you want to?

**Comment by jmisur** [comment]
Unfortunately you have to build from sources.
I didn't realise that the real problem is el-api impl and not hibernate validator in your case. I'm not sure however if we can completely disable constraint validation facilities, as it is one of the main features which we deliver, and usual Spring MVC code has it as a dep in one way or another.

**Comment by jmisur** [comment]
Hi again. I was wrong, we do publish snapshots.
```
 <repository>
         <id>snapshots-repo</id>
         <url>https://oss.sonatype.org/content/repositories/snapshots</url>
         <releases><enabled>false</enabled></releases>
         <snapshots><enabled>true</enabled></snapshots>
  </repository>

<dependency>
  <groupId>capital.scalable</groupId>
  <artifactId>spring-auto-restdocs-example</artifactId>
  <version>1.0.9-SNAPSHOT</version>
</dependency>
``` 

I furthermore reduced dependency on `javax.el-api` and `javax.servlet-api`. 

The problem however persists, that you have to have at least one validator implementation on the classpath. Spring is so integrated with validation (at least spring-boot) that when I removed the validation facilities completely it complained inside the very bean creation core...

Could you please experiment more and support us, or at least provide your example so we can investigate?

**Comment by filiphr** [comment]
>Hi again. I was wrong, we do publish snapshots.

I pulled it locally :).

>The problem however persists, that you have to have at least one validator implementation on the classpath. Spring is so integrated with validation (at least spring-boot) that when I removed the validation facilities completely it complained inside the very bean creation core...

I am not saying that you need to remove the it from your side. You just need to make it optional. Spring has that all over the place. [this](https://github.com/spring-projects/spring-framework/blob/master/spring-webmvc/src/main/java/org/springframework/web/servlet/config/annotation/WebMvcConfigurationSupport.java#L653) is one example where they use that.

There is a way to make it work. I can try later today and if I have time to provide you with a PR.

In a nutshel the `JacksonResultHandlers` should not create a constraint reader if there is no validation, or we make the `ConstraintReader` do nothing if there is no validation (currently it invokes something from rest docs itself). Actually the validation creation comes from rest docs. To check if validation is there or not something like this could be used:

```
private static final boolean validationPresent =
        ClassUtils.isPresent("javax.validation.Validator", JacksonResultHandlers.class.getClassLoader());
```

I tried just not creating the constraint reader, but I get some NPEs as it is not expected to be `nullable`.

**Comment by filiphr** [comment]
@jmisur can you reopen this, the issue is still the same. You are pulling in the validation api and if the user has no validation then this happens:

```java
javax.validation.ValidationException: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.
```

I can have a quick look over it during the weekend and help you out if you want.

**Comment by jmisur** [comment]
I know. I wasn't able to quickly find any project not using spring-boot and configure it for restdocs to test. If there is any online, you can point me to it.

**Comment by filiphr** [comment]
Awesome, thanks a lot for integrating it
