### ISSUE TITLE
Overriden methods should inherit the Javadoc

### ISSUE THREAD

**Issue by filiphr** [ScaCap/spring-auto-restdocs#126]
Let's say we have an interface:

```java
public interface MyInterface {

    /**
    * My comment for the name;
    */
    String getName();
}
```
And an implementation;

```java
public class MyImplementation implements MyInteface {

    private String name;
   
    @Override
    public String getName() {
        return name;
    }
}
```

I would expect that the documentation for the name to be picked up from the Javadoc of the `MyInterface`. If there is a comment on the overridden methods than that one needs to be taken. 

As a bonus the the Javadoc `inheritDoc` could be used as well (but this is not that important to me).

**Comment by jmisur** [comment]
Good idea. I agree it should work even without `inheritDoc`.

**Comment by filiphr** [comment]
My main idea was to work without the `inheritDoc`. It would be a bonus (or a new issue) to work with it. 

The `inheritDoc` can be used to inherit the parent documentation and add to it :smile:
