### ISSUE TITLE
Doesn't generate stub using WireMockRestDocs

### ISSUE THREAD

**Issue by TheMercuryBeat** [ScaCap/spring-auto-restdocs#138]
Hi! My problem is generating the WireMock stub using the step up in the documentation.

When I create a set up custom the stub aren't created and when I use the default MockMvc configuration works.

> 
     @fbenz 
     public void setUp() {
            this.mockMvc = MockMvcBuilders
                    .webAppContextSetup(context)
                    .alwaysDo(prepareJackson(objectMapper))
                    .alwaysDo(document("{class-name}/{method-name}",
                                       preprocessRequest(), commonResponsePreprocessor()))
                    .apply(documentationConfiguration(restDocumentation)
                                   .uris()
                                   .and().snippets()
                                   .withDefaults(curlRequest(), httpRequest(), httpResponse(),
                                                 requestFields(), responseFields(), pathParameters(),
                                                 requestParameters(), description(), methodAndPath(),
                                                 section()))
                    .build();
    }

> 

     @Test
      public void getTemplate() throws Exception {
        this.mockMvc.perform(get("/")
                                     .contentType(MediaType.APPLICATION_JSON)
                                     .accept(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andExpect(jsonPath("result", is("success")))
                .andExpect(jsonPath("version", is("0.0.1")))
                .andDo(WireMockRestDocs.verify().stub("getFlapTemplate"))
                .andDo(MockMvcRestDocumentation.document("getFlapTemplate", SpringCloudContractRestDocs.dslContract()));
    }

Is it possible to generate the WireMock stub with a custom's configuration?

Thanks in advance! :)

**Comment by jmisur** [comment]
Hi we didn't experiment with WireMock yet, but we'll take a look if there is anything we can do.

**Comment by fbenz** [comment]
I got it working by adding `new WireMockSnippet()` to the list of snippets:
```java
     public void setUp() {
            this.mockMvc = MockMvcBuilders
                    .webAppContextSetup(context)
                    .alwaysDo(prepareJackson(objectMapper))
                    .alwaysDo(document("{class-name}/{method-name}",
                                       preprocessRequest(), commonResponsePreprocessor()))
                    .apply(documentationConfiguration(restDocumentation)
                                   .uris()
                                   .and().snippets()
                                   .withDefaults(curlRequest(), httpRequest(), httpResponse(),
                                                 requestFields(), responseFields(), pathParameters(),
                                                 requestParameters(), description(), methodAndPath(),
                                                 section(), new WireMockSnippet()))
                    .build();
    }
```
It has to be added explicitly, because the auto configuration of Spring Cloud Contract Wiremock only works with Spring REST Docs and not with Spring Auto REST Docs. If run with Spring REST Docs, the following line adds the snippet: https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/restdocs/WireMockRestDocsConfiguration.java#L43

**Comment by jmisur** [comment]
@fbenz TODO - document this
