### ISSUE TITLE
Escaping pipe symbol

### ISSUE THREAD

**Issue by rgmonk** [ScaCap/spring-auto-restdocs#139]
I've got a problem with rendered text from annotation `@Pattern`.
A pipe symbol (|) within a regular expression breaks a table.

Spring Auto REST Docs is creation the following snippet:
```
|===
|Path|Type|Optional|Description

|id
|Integer
|true
|Item ID. +
javax.validation.constraints.NotBlank.

|description
|String
|true
|Item description. +
Size must be between 0 and 20 inclusive.

|patternString
|String
|true
|This is a regex pattern. +
Must match the regular expression `(TEST)|(LIVE)`.

|===
```
When HTML-documemnt is created by asciidoc (LIVE) is omitted. Also text isn't rendered in monospace. If one escapes the pipe (`(TEST)\|(LIVE)` you get the right result.
Can you add escaping of pipe symbols within regular expessions?
I've added a [sample project](https://github.com/rgmonk/playground/tree/master/rest-auto-doc-demo).

**Comment by jmisur** [comment]
Thanks for report. I'll check it out.
