### ISSUE TITLE
Possibility to translate the snippets header without creating custom snippets.

### ISSUE THREAD

**Issue by nielsenmg** [ScaCap/spring-auto-restdocs#143]
Hello,

It would be nice to have the possibility to translate the snippets header without creating a custom snippet and overriding the getHeader() method.

I don't know the best way to achieve this, but I thought about configuring the snippets headers on "MockMvcBase" like class.

**Comment by jmisur** [comment]
We already support snippet customization like `responseBodyAsType` and `failOnUndocumentedFields` and we could configure custom header in this way as well. However it would not apply to original restdocs snippets such as Curl request, HTTP request/response
