### ISSUE TITLE
Using POJOs for @PathVariable and @RequestParam

### ISSUE THREAD

**Issue by filiphr** [ScaCap/spring-auto-restdocs#148]
With Spring it is possible to use normal POJOs to substitute multiple `@PathVariable` or `@RequestParam`.

[This](http://www.logicbig.com/tutorials/spring-framework/spring-web-mvc/spring-request-param-data-binding/) blog post displays how it can be used.

I think it would be great if you can support something like this. I think that the `JacksonRequestFieldSnippet` can be somehow used to achieve this.

I think that the only thing is how to know which parameters you should use for mapping. For this I would propose that you allow creating the snippet with some custom annotation. If a parameter has that annotation then you can get that type and do the the same that what you are doing with the `JacksonRequestFieldSnippet`. Making the annotation customizable you will allow the users to define their own and they won't need to pull in `spring-auto-restdocs` into production.

**Comment by jmisur** [comment]
Interesting. I didn't know Spring tries to bind everything possible to method parameters. However we are relying quite heavily on spring annotations to determine various properties about query/path parameters. With POJOs we would loose a lot of information. It would be possible indeed with some custom annotations, but I'm not convinced we want to go that direction. We're trying to stick to standard way of doing things and this would need a lot of customizations. If you want you can submit a PR, but this is low prio for us now.

**Comment by lgringo** [comment]
Hello,

I've just done minimal for this request. I'd to do a PR. Do you have code formatting rules, or other rules I should know before submitting this PR ?

**Comment by jmisur** [comment]
idle issue. closing.

**Comment by filiphr** [comment]
This is more of a feature request? Why not leave it open? You can also mark it with some label that will show that it is up for the community, when it is closed people will think that it has been implemented or that you don't want this.
