### ISSUE TITLE
Standardize collections are rendered in the request and the response

### ISSUE THREAD

**Issue by lgringo** [ScaCap/spring-auto-restdocs#153]
Hello,

First, thank you for this awesome tool.

Can you standardize the way arrays and collections are rendered in the request and the response ?

![image](https://user-images.githubusercontent.com/1733463/32107449-e4788c02-bb2e-11e7-91f5-ce2027eb8ce9.png)

Is this example, categories in the request and the response are Array of String.

Here the code used to generate this documentation :
[spring-auto-restdocs-example.zip](https://github.com/ScaCap/spring-auto-restdocs/files/1422258/spring-auto-restdocs-example.zip)

**Comment by fbenz** [comment]
Thank you for your feedback. We will take a look.
