### ISSUE TITLE
Support for alternate response types or ExceptionHandlers

### ISSUE THREAD

**Issue by gludington** [ScaCap/spring-auto-restdocs#173]
It would be nice to be able to specify alternate responses for expected error codes.  For example:

```
@RequestMapping(value = "/login", method = POST, produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
    @ResponseStatus(HttpStatus.CREATED)
    @ResponseBody
    public ResponseEntity<LoginResponse> login(@RequestParam String username, @RequestParam String password)
```
There may be other expected errors that do not have that field structure, or are a different class altogether and would return a different response code; for example, a 403 Forbidden or 404 Not Found for a bad authorization attempt, or a 500 for an unknown error.  Is there any provision for such alternate codes and response bodies, or do they need to be placed in the asciidoc directly?

**Comment by jmisur** [comment]
For every scenario you want to document, create a test producing desired result and include relevant generated snippets in overall documentation of the endpoint. What we do ourselves is we include request/response snippets right after section snippet to document exception cases, e.g. 
```
[[resources-user]]
== User

Blabla documenting user endpoints here.

include::{snippets}/user/get/auto-section.adoc[]

include::{snippets}/user/create/auto-section.adoc[]

===== Example request/response with validation errors
include::{snippets}/user/create-errors/curl-request.adoc[]
include::{snippets}/user/create-errors/http-response.adoc[]
```

**Comment by gludington** [comment]
Thank you for the reply; I have created separate tests with the failure cases, and that works to generate example responses, but the generated auto-response-fields.adoc from the invalid response test cases show the structure of the successful response, rather than the structure of the error response.  That is what I am trying to create, hopefully without creating dummy extra methods in the API whose only purpose is to declare specific error classes as their return value in order to generate snippets for documentation.

**Comment by jmisur** [comment]
As we do not know what kind of structures you return on various error responses, we only statically analyze the method's return class. 
What you might want to do in the end, is to create separate handcrafted section in your documentation describing API responses in different error cases and status codes, which should apply throughout your API. In our case it's only 1 alternative structure for error response which is applied in the entire API, so we don't need to document it separately for each endpoint, only provide example curl request / http response to see what message or content will it contain if you send invalid value, as an example.
Anyway you can help yourself with this a bit, request/response field snippets have some yet undocumented features, e.g. `responseFields().responseBodyAsType(ErrorResult.class)` which you can use to override default response structure. Check https://github.com/ScaCap/spring-auto-restdocs/blob/master/spring-auto-restdocs-example/src/test/java/capital/scalable/restdocs/example/items/ItemResourceTest.java#L119

**Comment by gludington** [comment]
Thank you very much - the responseFields.responseBodyAsType does exactly what I was looking for, and I can embed/link snippets generated from an errored test case as needed.
