### ISSUE TITLE
Upgrade to Spring REST Docs 2.0.0

### ISSUE THREAD

**Issue by fbenz** [ScaCap/spring-auto-restdocs#176]
~~This upgrade should involve adding support for WebTestClient and thus involves some work.~~

We have to be aware that Spring REST Docs 2 requires Java 8 and Spring Framework 5.

**Comment by jmisur** [comment]
We need to be backwards compatible. We should be able to support spring-boot 2 / restdocs 2 with current implementation if there are no breaking changes.
Regarding WebTestClient, we can implement the support when need arises, otherwise just wait for community PR.

**Comment by fbenz** [comment]
I agree that we should separate upgrading to Spring REST Docs 2 and supporting WebTestClient. This issue only tracks the upgrade to version 2.

**Comment by Josef-Reichardt** [comment]
Sry for commenting this clused issue, but is it correct that it is currently not possible to use spring-auto-restdocs with the WebTestClient? Are there any plans or is there already another issue in github?

**Comment by fbenz** [comment]
@Josef-Reichardt WebTestClient is not supported at the moment and there are no plans to support it. Contributions to support is are welcome though.
