### ISSUE TITLE
Response fields Type of Var for Calendar field?

### ISSUE THREAD

**Issue by melissapalmer** [ScaCap/spring-auto-restdocs#195]
Hi 

I am getting a Var for Type in Response for fields in POJO that are of type Calendar?
Why is this? And how can I change to that the Type something else such as Calendar or String of Format YYYY-MM-dd say. 

Thanks in advance
Melissa

**Comment by fbenz** [comment]
You are saying that in your case a request or response like
```Java
import java.util.Calendar;

class SomeRequest {
    private Calendar calendar;
}
```
ends up as

| Path  | Type | Optional | Description |
| ------------- | ------------- | ------------- | ------------- |
| calendar | Var | true |  |

or?

It depends on the Jackson (de)serializer that you are using for Calendar. If the serializer tells Jackson that it can be any type (by calling the corresponding method), Spring Auto REST Docs translates it to `Var`. If the serializer would say that it is a string, Spring Auto REST Docs would translate it to `String`. So it just depends on the (de)serializer. By default `java.util.Calendar` is converted into an integer and this is shown correctly by Spring Auto REST Docs.

An example for a serializer that tells Jackson that the type is a string can be found in the example project: https://github.com/ScaCap/spring-auto-restdocs/blob/2f4959764ebf5bbaf89329123d6ec3da36d935d0/spring-auto-restdocs-example/src/main/java/capital/scalable/restdocs/example/jackson/MoneySerializer.java#L44

**Comment by melissapalmer** [comment]
Hi fbenz, thank you for the quick response!  

That was my issue I had a custom serializer but that not overridden the acceptJsonFormatVisitor function.  I added that and now get:

Path | Type | Optional | Description
------ | -------|------|------
calendar | String|true| Date person was born

Which is what I was looking for. 

**One more question however:** what is the best way to show the format of this date String, without having to add JavaDoc to each field of type Calendar? 

Example of what might be looking for below: (or adding date info at top level of whole documentation page)

Path | Type | Optional | Description
------ | -------|------|------
calendar | String|true| Date person was born **Format yyyy-MM-dd**




I have a serializer as follows: 
```java
public class CalendarToDateStringSerializer extends StdSerializer<Calendar> {
    public CalendarToDateStringSerializer() {
        super(Calendar.class);
    }

    @Override
    public void serialize(Calendar value, JsonGenerator gen, SerializerProvider serializers) throws IOException, JsonProcessingException {
        if (value != null) {

            String formatted = GlobalFormatSettings.getDateFormatter().format(value.getTime());

            gen.writeString(formatted);
        }
    }

    @Override
    public void acceptJsonFormatVisitor(JsonFormatVisitorWrapper visitor, JavaType typeHint) throws JsonMappingException {
        if (visitor != null) {
            visitor.expectStringFormat(typeHint);
        }
    }

}
```
where GlobalFormatSettings is : 

```java
public class GlobalFormatSettings {
    public static final String DATE_FORMAT_PATTEN = "yyyy-MM-dd";
    public static SimpleDateFormat dateFormatter = new SimpleDateFormat(DATE_FORMAT_PATTEN);

    public static SimpleDateFormat getDateFormatter() {
        return dateFormatter;
    }
}

**Comment by fbenz** [comment]
I see two options:
1. Adding the text to each field's Javadoc as you described.
2. Creating a custom constraint like `@CalendarDate`.

Example of a custom constraint is `@Id` in the example project: https://github.com/ScaCap/spring-auto-restdocs/blob/master/spring-auto-restdocs-example/src/main/java/capital/scalable/restdocs/example/constraints/Id.java#L38
The validation can be omitted if it is just used for the documentation, i.e. just keeping `@Constraint(validatedBy = {})` and adding no other annotations like `@Pattern`.

The text for the documentation is coming from a properties file:
https://github.com/ScaCap/spring-auto-restdocs/blob/master/spring-auto-restdocs-example/src/main/resources/org/springframework/restdocs/constraints/ConstraintDescriptions.properties#L4

The description of the constraint "Must be a valid ID" ends up in the description: https://htmlpreview.github.io/?https://github.com/ScaCap/spring-auto-restdocs/blob/master/spring-auto-restdocs-example/generated-docs/index.html#resources-items-get

**Comment by melissapalmer** [comment]
Thank You Florian!   I was hoping not to have to write docs/code for every-time, as the formatting is getting picked up automatically by the serializer. I will look and see if there is something else we could use. Thanks Melissa
