### ISSUE TITLE
How to deal with servlet filters? 

### ISSUE THREAD

**Issue by xuanyimo** [ScaCap/spring-auto-restdocs#200]
Env:
- JDK 1.8
- auto-restdocs 1.0.10
- spring-restdocs 1.2.3.RELEASE
- spring-security 4.2.3.RELEASE

QUESTION:
I want to test `auth`. My handlerUrl is `/login`.
MyTestCase:
```
      this.mvc
            .perform(post("/login")
                .param("username", "123456")
                .param("password", "123456"))
            .andExpect(status().is3xxRedirection())
            .andExpect(result ->
                assertFalse(result.getResponse()
                    .getRedirectedUrl()
                    .equalsIgnoreCase("/login_page?error")));
```

Generated `section-snippet`:
```
[[resources-user-test-login-success]]
=== { class - name } / { method - name }

include::{snippets}/user-test/login-success/auto-method-path.adoc[]

include::{snippets}/user-test/login-success/auto-description.adoc[]
```

Its obvious that '{class-name}/{method-name}' dose not be parsed.
I had known it was due to servlet's filters, its didn't have a `handlerMethod`.

Would you please try to solve this question?
I just want it to do not show '{ class - name } / { method - name }'

**Comment by fbenz** [comment]
Currently, Spring Auto REST Docs only supports Spring Web MVC endpoints. The [login endpoint](https://github.com/spring-projects/spring-security/blob/a82cab7afdb1fc58830b1c415f1874d36b2c6c92/web/src/main/java/org/springframework/security/web/authentication/LoginUrlAuthenticationEntryPoint.java) that is used here is not a Spring Web MVC endpoint. Therefore, I propose to either use Spring REST Docs or to manually document this endpoint

**Comment by xuanyimo** [comment]
Thanks a lot! I did it with below code: 
```java
      this.mvc
            .perform(post("/login")
                .with(request -> {
                    request.setAttribute(BEST_MATCHING_PATTERN_ATTRIBUTE, "/login");
                    OperationAttributeHelper.initRequestPattern(request);
                    return request;
                })
                .param("username", "123456")
                .param("password", "123456"))
            .andExpect(status().is3xxRedirection())
            .andExpect(result ->
                assertFalse(result.getResponse()
                    .getRedirectedUrl()
                    .equalsIgnoreCase("/login_page?error")))
            .andDo(document("login"));
```

The request postProcessor solve a problem that `snippet` don't have `path`(Only `method`, just like ``GET ``. **There is a space after 'GET'**, `asciidoctor`  can't resolve this. ) 
`document("login")` override the name '{ class - name } / { method - name }'.

That is maybe a solution !^_^

**Comment by jmisur** [comment]
Nice hack! I see you did digging inside the code a bit. 
However keep in mind you're dealing with internals which might break in the future. Also the scope of the snippet is limited to method and description, because other snippets would fail. That's why we won't document or encourage people to do this ;)

**Comment by xuanyimo** [comment]
I hope our Spring Auto RESTDocs can deal with this situation in the future! It will be better!
