### ISSUE TITLE
Documentation should point to stable version

### ISSUE THREAD

**Issue by ractive** [ScaCap/spring-auto-restdocs#201]
The documentation on https://scacap.github.io/spring-auto-restdocs/ points to the latest snapshot release (it seems). I would expect it to point to the latest stable version.

I was wondering why my `@RequestHeader` arguments aren't documented although the request headers snippets are mentioned in the "current" [doc](https://scacap.github.io/spring-auto-restdocs/#snippets-request-headers). Then I realized that this feature is not yet available in the 1.0.10 release. 😢

It could also help if the documented version would be mentioned in the preamble of the documentation itself.

**Comment by fbenz** [comment]
Right, the documentation at https://scacap.github.io/spring-auto-restdocs/ is always taken from master and that might be confusing. The Readme lists the documentation of the releases but the documentation itself does not contain the version in a prominent place. But the documentation already contains the version and thus it should be straight forward to add it to the preamble.

FYI: We released 1.0.11 today and it contains all features that are currently on master.

**Comment by ractive** [comment]
Thanks for releasing 1.0.11... 🎉
