### ISSUE TITLE
Show the object type wrapped by Optional in Query Params

### ISSUE THREAD

**Issue by daniellwu** [ScaCap/spring-auto-restdocs#204]
If a query parameter is of the type Optional, it would be nice for the generated REST doc to say what the object wrapped by the Optional is. For example, if it's `Optional<String>`, in the Query parameters "Type" column, show `Optional<String>` (or something to that affect) instead of "Object"?

In the attached screen shot, partialPid parameter is an `Optional<String>`
![image](https://user-images.githubusercontent.com/1897477/34802490-c3383428-f622-11e7-9cbd-7d4785ce1933.png)

**Comment by fbenz** [comment]
Thank you for bringing this up. The type for `Optional<String>` should be `String`. The optionality should only affect the `Optional` column. One issue is that Spring Auto REST Docs has Java 7 as the baseline. It can still be added via reflection, but it's a bit ugly. The baseline for Spring Auto REST Docs 2 will be Java 8 (same as for  Spring REST Docs 2) and thus it will be easy to add there.

**Comment by fbenz** [comment]
Supported was added in the meantime and is included in the 2.0.2 release. See https://github.com/ScaCap/spring-auto-restdocs/pull/230
