### ISSUE TITLE
Consider aligning failOnUndocumentedFields to Spring REST Docs

### ISSUE THREAD

**Issue by fbenz** [ScaCap/spring-auto-restdocs#217]
There are two differences right now:

1. The default in Spring REST Docs is to fail on undocumented fields. This is the opposite in Spring Auto REST Docs.
2. In Spring REST Docs one either uses `requestFields` to get and error or `relaxedRequestFields` to ignore undocumented fields. In Spring Auto REST Docs one uses `requestFields()` to ignore undocumented fields and `requestFields().failOnUndocumentedFields(enabled)` to explicitly enable or disable the feature.

**Comment by jmisur** [comment]
Closing as there was no need to consolidate.
