### ISSUE TITLE
Links for the examples (1.0.13 and 2.0.1) are broken.

### ISSUE THREAD

**Issue by bessels** [ScaCap/spring-auto-restdocs#232]
When I click on the 'here' link in the documentation, as in "The generated documentation of the example project can be viewed here."

I get the following error:
Error: Cannot load file https://raw.githubusercontent.com/ScaCap/spring-auto-restdocs/master/spring-auto-restdocs-example/generated-docs/index.html (2.0.1)
Error: Cannot load file https://raw.githubusercontent.com/ScaCap/spring-auto-restdocs/master/spring-auto-restdocs-example/generated-docs/index.html (1.0.13).

Can this have something to do with the new 2.x release or the separation of the 'examples' project iirc read about it here. 

Half year or so ago I tried to compile the examples but had problems with it, so sadly I have to rely on the Github documentation examples pages atm.....

**Comment by fbenz** [comment]
Thanks for bringing this up. You are right that this broke when we split up into 1.x and 2.x and introduced two example projects for 2.x. The correct links are:

2.0.1:
* [Java example](https://htmlpreview.github.io/?https://github.com/ScaCap/spring-auto-restdocs/blob/master/samples/java-webmvc/generated-docs/index.html)
* [Kotlin example](https://htmlpreview.github.io/?https://github.com/ScaCap/spring-auto-restdocs/blob/master/samples/kotlin-webmvc/generated-docs/index.html)

1.0.13
* [Java example](https://htmlpreview.github.io/?https://github.com/ScaCap/spring-auto-restdocs/blob/1.0.x/spring-auto-restdocs-example/generated-docs/index.html)

We still have to fix it in the documentation.

**Comment by wolverine2710** [comment]
Thanks for the links. Very much appreciated
