### ISSUE TITLE
Custom ConstraintReader allowed?

### ISSUE THREAD

**Issue by connorsadlervelo** [ScaCap/spring-auto-restdocs#233]
Hi,

I'd like to use a custom ConstraintReader.
I wrote a snippet to install this - please see below

Is this sort of thing allowed or am I using an internal API, here?
Could you publish an API to allow installation of a custom ConstraintReader?
I'd be able to submit a PR for this I believe, given a bit of time grabbing the code etc.

Reason for this is: I have a custom class which I would like to document exactly the same, everywhere it's used, without having to put identical javadoc on each member variable.

TIA,

Connor

```
package com.mycomp.mymodule.controller

import capital.scalable.restdocs.constraints.ConstraintReader
import org.springframework.restdocs.operation.Operation
import org.springframework.restdocs.snippet.Snippet

class XXXMyConfigSnippet implements Snippet {
    @Override
    void document(Operation operation) throws IOException {
        println("document: " + operation)

        ConstraintReader constraintReader = (ConstraintReader) operation.getAttributes().get(ConstraintReader.class.getName());
        if (!(constraintReader instanceof XXXMyeloConstraintReader)) {
            println("replacing ConstraintReader with custom class")
            operation.attributes.put(ConstraintReader.class.getName(), new XXXMyConstraintReader(constraintReader));
        }

    }
}
```

**Comment by jmisur** [comment]
Hi Connor, you are definitely using internal API and the default implementation is quite non-trivial at this point. So by replacing it this way you might loose a lot of stuff along. There is no official support or roadmap for spring-auto-restdocs extensibility itself. 
Could you please elaborate more about what you're trying to achieve? Is it just documentation of a single field (which is custom pojo) used in other pojos, so you don't want to copy-paste? Could you provide some example?

**Comment by connorsadlervelo** [comment]
Hi jmisur,
Yes that is the use-case, you have summarisedit perfectly

// custom serializer/deserializer here
class MyUsefulType {
   private String myUsefulValue;
}
class MyRequestOne {
  ...
  private MyUsefulType useful;
  ...
}
class MyRequestTwo {
  ...
  private MyUsefulType useful;
  ...
}
class MyRequestThree {
  ...
  private MyUsefulType useful;
  ...
}

There are a bunch of POJOs in different modules which all declare a member variable of type MyUsefulType. (They have other member variables aswell)
MyUsefulType has a custom serializer so goes into the JSON as a simple String value.
This is almost identical to the issue described here:
https://github.com/ScaCap/spring-auto-restdocs/issues/195

I tried declaring javadocs on the member variables but unfortunately ran into the problem described here: https://github.com/ScaCap/spring-auto-restdocs/issues/102
MyRequestOne is in a jar file, and the build which uses MyRequestOne cannot access the javadoc json files for MyRequestOne

So I ended up at this Constraint suggestion from https://github.com/ScaCap/spring-auto-restdocs/issues/195
I then have to put a constraint on every field, which isn't too bad, and also they need a custom .properties file for the constraint descriptions.
It would be easier if I could put this documentation into MyUsefulType somehow instead.
e.g. an annotation on MyUsefulType?

Thanks again for your help,

Connor

**Comment by connorsadlervelo** [comment]
PS In the code in the original post, I haven't lost anything per se because my custom constraint reader calls all the original code by default.
I can just add to the default logic with some custom code in certain circumstances

**Comment by jmisur** [comment]
Hi, documentation coming from jar files are definitely possible, check our [samples folder organisation with shared POJOs](https://github.com/ScaCap/spring-auto-restdocs/tree/master/samples).
For a custom constraint reader, there wasn't really any need whatsoever. If your problem is fixed by using shared jar - great! If not, feel free to submit a PR.
