### ISSUE TITLE
Doclet for Java 9+

### ISSUE THREAD

**Issue by eomeara** [ScaCap/spring-auto-restdocs#243]
Spring Boot 2.0.2, Gradle 4.8, Spring Auto RestDocs 2.0.1, macOS 10.13.5, JDK 10.0.1-zulu, SDKMAN 5.6.4+305.

It appears that the build is not using the standard doclet (from Oracle) and hence the -d option is not supported. Some of the gradle error output is shown below. Note that the output for running **javadoc --help** at the command line follows the error output and indicates that the javadoc command does support the oracle standard doclet under some conditions, but not with Auto Rest Docs. On reviewing jdk 10 it appears the standard doclet is not supported programatically. Note ``options.doclet`` in part of  ``build.gradle`` below. Also note ``destinationDir``. Perhaps there should be a jdk9+ version that does not use the ``com.sun`` namespace which was deprecated in jdk9 and partly removed in jdk10.

Part of build.gradle
===============
```
task jsonDoclet(type: Javadoc, dependsOn: compileJava) {
    source = sourceSets.main.allJava
    classpath = sourceSets.main.compileClasspath
    destinationDir = javadocJsonDir
    options.docletpath = configurations.jsondoclet.files.asType(List)
    options.doclet = 'capital.scalable.restdocs.jsondoclet.ExtractDocumentationAsJsonDoclet'
    options.memberLevel = JavadocMemberLevel.PACKAGE
}
```

Part of Gradle output
=======================================================================
> Task :jsonDoclet FAILED
javadoc: warning - The old Doclet and Taglet APIs in the packages
com.sun.javadoc, com.sun.tools.doclets and their implementations
are planned to be removed in a future JDK release. These
components have been superseded by the new APIs in jdk.javadoc.doclet.
Users are strongly recommended to migrate to the new APIs.
javadoc: error - invalid flag: -d
Usage: javadoc [options] [packagenames] [sourcefiles] [@files]
  -overview <file>                 Read overview documentation from HTML file
  -public                          Show only public classes and members
  -protected                       Show protected/public classes and members (default)
  -package                         Show package/protected/public classes and members
  -private                         Show all classes and members
  -help                            Display command line options and exit
  -doclet <class>                  Generate output via alternate doclet
  -docletpath <path>               Specify where to find doclet class files
  --module-source-path <path>      Specify where to find input source files for multiple modules
  --upgrade-module-path <path>     Override location of upgradeable modules
  --module-path <path>, -p <path>  Specify where to find application modules
  --add-modules <module>(,<module>)*
                                   Root modules to resolve in addition to the initial modules,
                                   or all modules on the module path if <module> is ALL-MODULE-PATH.
  --limit-modules <module>(,<module>)*
                                   Limit the universe of observable modules
  --source-path <path>             Specify where to find source files
  -sourcepath <path>               Specify where to find source files
  --class-path <path>              Specify where to find user class files
  -classpath <path>                Specify where to find user class files
  -cp <path>                       Specify where to find user class files
  -exclude <pkglist>               Specify a list of packages to exclude
  -subpackages <subpkglist>        Specify subpackages to recursively load
  -breakiterator                   Compute first sentence with BreakIterator
  -bootclasspath <path>            Override location of platform class files
                                   used for non-modular releases
  --system <jdk>                   Override location of system modules used
                                   for modular releases.
  -source <release>                Provide source compatibility with specified release
  --release <release>              Provide source compatibility with specified release
  -extdirs <dirlist>               Override location of installed extensions
  -verbose                         Output messages about what Javadoc is doing
  -locale <name>                   Locale to be used, e.g. en_US or en_US_WIN
  -encoding <name>                 Source file encoding name
  -quiet                           Do not display status messages
  -J<flag>                         Pass <flag> directly to the runtime system
  -X                               Print a synopsis of nonstandard options and exit

GNU-style options may use = instead whitespace to separate the name of an option
from its value.

1 error

FAILURE: Build failed with an exception.

Javadoc Usage
=======================================================================
Usage:
    javadoc [options] [packagenames] [sourcefiles] [@files]
where options include:
    --add-modules <module>(,<module>)*
                  Root modules to resolve in addition to the initial modules,
                  or all modules on the module path if <module> is
                  ALL-MODULE-PATH.
    -bootclasspath <path>
                  Override location of platform class files used for non-modular
                  releases
    -breakiterator
                  Compute first sentence with BreakIterator
    --class-path <path>, -classpath <path>, -cp <path>
                  Specify where to find user class files
    -doclet <class>
                  Generate output via alternate doclet
    -docletpath <path>
                  Specify where to find doclet class files
    -encoding <name>
                  Source file encoding name
    -exclude <pkglist>
                  Specify a list of packages to exclude
    --expand-requires <value>
                  Instructs the tool to expand the set of modules to be
                  documented. By default, only the modules given explicitly on
                  the command line will be documented. A value of "transitive"
                  will additionally include all "requires transitive"
                  dependencies of those modules. A value of "all" will include
                  all dependencies of those modules.
    -extdirs <dirlist>
                  Override location of installed extensions
    --help, -help
                  Display command line options and exit
    --help-extra, -X
                  Print a synopsis of nonstandard options and exit
    -J<flag>      Pass <flag> directly to the runtime system
    --limit-modules <module>(,<module>)*
                  Limit the universe of observable modules
    -locale <name>
                  Locale to be used, e.g. en_US or en_US_WIN
    --module <module>(,<module>)*
                  Document the specified module(s)
    --module-path <path>, -p <path>
                  Specify where to find application modules
    --module-source-path <path>
                  Specify where to find input source files for multiple modules
    -package
                  Show package/protected/public types and members. For 
                  named modules, show all packages and all module details.
    -private
                  Show all types and members. For named modules,
                  show all packages and all module details.
    -protected
                  Show protected/public types and members (default). For
                  named modules, show exported packages and the module's API.
    -public
                  Show only public types and members. For named modules,
                  show exported packages and the module's API.
    -quiet        Do not display status messages
    --release <release>
                  Provide source compatibility with specified release
    --show-members <value>
                  Specifies which members (fields, methods, etc.) will be
                  documented, where value can be one of "public", "protected",
                  "package" or "private". The default is "protected", which will
                  show public and protected members, "public" will show only
                  public members, "package" will show public, protected and
                  package members and "private" will show all members.
    --show-module-contents <value>
                  Specifies the documentation granularity of module
                  declarations. Possible values are "api" or "all".
    --show-packages <value>
                  Specifies which modules packages will be documented. Possible
                  values are "exported" or "all" packages.
    --show-types <value>
                  Specifies which types (classes, interfaces, etc.) will be
                  documented, where value can be one of "public", "protected",
                  "package" or "private". The default is "protected", which will
                  show public and protected types, "public" will show only
                  public types, "package" will show public, protected and
                  package types and "private" will show all types.
    -source <release>
                  Provide source compatibility with specified release
    --source-path <path>, -sourcepath <path>
                  Specify where to find source files
    -subpackages <subpkglist>
                  Specify subpackages to recursively load
    --system <jdk>
                  Override location of system modules used for modular releases
    --upgrade-module-path <path>
                  Override location of upgradeable modules
    -verbose      Output messages about what Javadoc is doing
    --version     Print version information

Provided by the Standard doclet:
    --add-stylesheet <file>
                  Additional stylesheet file for the generated documentation
    --allow-script-in-comments
                  Allow JavaScript in options and comments
    -author       Include @author paragraphs
    -bottom <html-code>
                  Include bottom text for each page
    -charset <charset>
                  Charset for cross-platform viewing of generated documentation
    -d <directory>
                  Destination directory for output files
    -docencoding <name>
                  Specify the character encoding for the output
    -docfilessubdirs
                  Recursively copy doc-file subdirectories
    -doctitle <html-code>
                  Include title for the overview page
    -excludedocfilessubdir <name>:..
                  Exclude any doc-files subdirectories with given name
    -footer <html-code>
                  Include footer text for each page
    --frames      Enable the use of frames in the generated output (default)
    -group <name> <g1>:<g2>...
                  Group specified elements together in overview page
    -header <html-code>
                  Include header text for each page
    -helpfile <file>
                  Include file that help link links to
    -html4        Generate HTML 4.01 output
    -html5        Generate HTML 5 output
    --javafx, -javafx
                  Enable javafx functionality
    -keywords     Include HTML meta tags with package, class and member info
    -link <url>   Create links to javadoc output at <url>
    -linkoffline <url1> <url2>
                  Link to docs at <url1> using package list at <url2>
    -linksource   Generate source in HTML
    --main-stylesheet <file>, -stylesheetfile <file>
                  File to change style of the generated documentation
    -nocomment    Suppress description and tags, generate only declarations
    -nodeprecated
                  Do not include @deprecated information
    -nodeprecatedlist
                  Do not generate deprecated list
    --no-frames   Disable the use of frames in the generated output
    -nohelp       Do not generate help link
    -noindex      Do not generate index
    -nonavbar     Do not generate navigation bar
    -noqualifier <name1>:<name2>:..
                  Exclude the list of qualifiers from the output
    -nosince      Do not include @since information
    -notimestamp  Do not include hidden time stamp
    -notree       Do not generate class hierarchy
    --override-methods (detail|summary)
                  Document overridden methods in the detail or summary sections
    -overview <file>
                  Read overview documentation from HTML file
    -serialwarn   Generate warning about @serial tag
    -sourcetab <tab length>
                  Specify the number of spaces each tab takes up in the source
    -splitindex   Split index into one file per letter
    -tag <name>:<locations>:<header>
                  Specify single argument custom tags
    -taglet       The fully qualified name of Taglet to register
    -tagletpath   The path to Taglets
    -top <html-code>
                  Include top text for each page
    -use          Create class and package usage pages
    -version      Include @version paragraphs
    -windowtitle <text>
                  Browser window title for the documentation

GNU-style options may use = instead of whitespace to separate the name of an
option from its value.

**Comment by Josef-Reichardt** [comment]
Is there already someone working on this?

**Comment by jmisur** [comment]
Would you be interested in proposing a fix via PR?

**Comment by Josef-Reichardt** [comment]
I will try to supply a PR this week. But I can't do the dokka part because I'm sadly not familiar with kotlin yet.

**Comment by marceloverdijk** [comment]
+1 for Java9+ support.

**Comment by rubenpirotteQNH** [comment]
We would like to help making it java 9+ compatibele, but we need a clearer view of how you would like to see it solved.

- Do we create a new branch where we implement umldoclet version 2.x , making it java 9+ compatible?
- I do not understand the issue you describe here:
https://github.com/ScaCap/spring-auto-restdocs/pull/251#issuecomment-418352493

> our current Travis CI setup only uses the same JDK for all projects in this repository.

**Comment by jmisur** [comment]
Hi @rubenpirotteQNH, we'll determine the next steps shortly and let you know.

**Comment by juleshouben** [comment]
I added a pull request to make the doclet work with the -d provider by gradle. See #259 for more information.
