### ISSUE TITLE
@JsonTypeInfo and @JsonSubTypes is it possible to pick which subtype to show in the Request fields?

### ISSUE THREAD

**Issue by melissapalmer** [ScaCap/spring-auto-restdocs#244]
Related to issue [112](https://github.com/ScaCap/spring-auto-restdocs/issues/112)

Is it possible to avoid the merge ? of a SubType for the Request Object?

**Comment by jmisur** [comment]
What would you propose instead? Multiple subsections describing each type? What if common-to-custom fields are 10:1? Than they would be duplicated all over. Or something like specifying type automatically in custom fields' description? There are pros and cons to each. I would be happy to hear how it would work for you.
