### ISSUE TITLE
Including Spring Restdocs snippets in AutoDocumentation.section

### ISSUE THREAD

**Issue by kschulst** [ScaCap/spring-auto-restdocs#248]
How can I include snippets generated by core Spring Restdocs into spring-auto-restdocs sections?

I am aware of
https://scacap.github.io/spring-auto-restdocs/#snippets-section-custom-snippet

I want to render core spring restdocs HATEOAS link snippets inside the very convenient section snippet that spring-auto-restdocs provides.

**Comment by kschulst** [comment]
I have looked a bit into this and everything leads to:
The `SectionSnippet` class:

The way spring-auto-restdocs renders the section:
```
    private SectionSupport getSectionSnippet(Operation operation, String snippetName) {
        return getDefaultSnippets(operation).stream()
                .filter(snippet -> snippet instanceof SectionSupport)
                .map(snippet -> (SectionSupport) snippet)
                .filter(snippet -> snippetName.equals(snippet.getFileName()))
                .findFirst()
                .orElseGet(() -> SnippetRegistry.getClassicSnippet(snippetName));
    }
```
...requiring the Snippet to implement a spring-auto-restdocs interface (`SectionSupport`) in effect forces the spring-restdocs snippets to end up in the `orElseGet` and thus fetched from the `capital.scalable.restdocs.SnippetRegistry`. But `SnippetRegistry` is locked down and cannot be expanded upon.

Would you be interested in a pull request to loosen up the SnippetRegistry a bit, making it possible to register other snippets?

And also even maybe preregister all "classic snippets" in the `SnippetRegistry`?
As of now, only the following snippets are available:
```
CURL_REQUEST
HTTPIE_REQUEST
HTTP_REQUEST
HTTP_RESPONSE
```

(And please let me know if there are any other way of accomplishing this.)

**Comment by jmisur** [comment]
Hi @kschulst, if you can make a PR proposal how to make SnippetRegistry nicely extensible or configurable, we'll very welcome it.

**Comment by kschulst** [comment]
@jmisur I have submitted a pull request for this...
