### ISSUE TITLE
Localization support some problem

### ISSUE THREAD

**Issue by qinkangdeid** [ScaCap/spring-auto-restdocs#265]
I have encountered some difficulties in this step.i use the [example](https://github.com/ScaCap/spring-auto-restdocs/tree/master/samples/java-webmvc) , and then i modify`SnippetMessages.properties` file, add the following information:

<img width="1224" alt="auth" src="https://user-images.githubusercontent.com/17582522/47356194-e8734480-d6f5-11e8-938b-aba8cb71b2a1.png">

I'm a Chinese, so I want to change the title in the  `auto-section.adoc`  file to the language of my country. when I perform a unit test,the title of the  `auto-authorization.adoc[]`  file has become garbled，like this: 

<img width="300" alt="auth2" src="https://user-images.githubusercontent.com/17582522/47356460-b57d8080-d6f6-11e8-8d3d-3edf3457acbc.png">

I saw some source code：read the ` SnippetMessages.properties`  file in the SnippetTranslationResolver class.

<img width="1321" alt="auth3" src="https://user-images.githubusercontent.com/17582522/47356657-43596b80-d6f7-11e8-8f3c-b1111e1d99a3.png">

 `Locale.getDefault()` Showing the language of my country：CN

But the information from internationalization is garbled.

Is it wrong for me to understand ? What can I do to correct my problem?
Thanks again.

**Comment by qinkangdeid** [comment]
Oh, my god. It’s my understanding is wrong. I used the wrong text.I didn't even use unicode characters. I made a  low-level mistake.

`authorization=\u6388\u6743\u4fe1\u606f`

**Comment by fbenz** [comment]
So your solution is to use `authorization=\u6388\u6743\u4fe1\u606f`? If everything is UTF-8 encoded, one should be able to use the characters directly. But the issue might be that Java properties files are ISO 8859-1 encoded by default.
