### ISSUE TITLE
Question: Compatibility to restdocs-api-spec for generating OpenAPI YAML

### ISSUE THREAD

**Issue by cnsgithub** [ScaCap/spring-auto-restdocs#281]
Hey guys, 

I am trying to use Spring Auto REST Docs to generate OpenAPI 3 YAML.

Since I am using maven I integrated https://github.com/BerkleyTechnologyServices/restdocs-spec maven plugin with experimental OpenAPI 3 support (probably will provide a PR for that on github).

In addition I am using `MockMvcRestDocumentationWrapper ` (https://github.com/ePages-de/restdocs-api-spec) to generate `resource.json `when doing integration tests.

However, I'd like to use Spring Auto REST Docs as an extension to Spring REST Docs and can't get it to work.

Snippets from Spring Auto REST Docs are generated and located in `target/generated-snippets/{method-name}/auto-*.adoc`

But unfortunately `resource.json `does not contain any information from javadocs/introspection processed by Spring Auto REST Docs.

I just tried to change all occurrences of `MockMvcRestDocumentation `to `MockMvcRestDocumentationWrapper `and noticed that there is no equivalent for `MockMvcRestDocumentation.documentationConfiguration `in your wrapper.

However, this call to `documentationConfiguration `seems to be needed for Spring Auto REST Docs to register the `AutoDocumentation `snippet generators.

Appreciate your help.

This is what I tried without success:

```java
        mvc = MockMvcBuilders.webAppContextSetup(webApplicationContext)
                .alwaysDo(JacksonResultHandlers.prepareJackson(objectMapper))
                .alwaysDo(MockMvcRestDocumentationWrapper.document("ControllerIT/{method-name}", MockMvcRestDocumentationWrapper.resourceDetails(),
                        Preprocessors.preprocessRequest(), Preprocessors.preprocessResponse(ResponseModifyingPreprocessors.replaceBinaryContent(),
                                ResponseModifyingPreprocessors.limitJsonArrayLength(objectMapper), Preprocessors.prettyPrint()), CliDocumentation.curlRequest(), HttpDocumentation.httpRequest(), HttpDocumentation.httpResponse(),
                        AutoDocumentation.requestFields(), AutoDocumentation.responseFields(), AutoDocumentation.pathParameters(),
                        AutoDocumentation.requestParameters(), AutoDocumentation.description(), AutoDocumentation.methodAndPath(),
                        AutoDocumentation.section()))
                .apply(MockMvcRestDocumentation.documentationConfiguration(restDocumentation)
                        .uris()
                        .withScheme("http")
                        .withHost("localhost")
                        .withPort(8080)
                        .and()
                        .snippets()
                        .withDefaults(CliDocumentation.curlRequest(), HttpDocumentation.httpRequest(), HttpDocumentation.httpResponse(),
                                AutoDocumentation.requestFields(), AutoDocumentation.responseFields(), AutoDocumentation.pathParameters(),
                                AutoDocumentation.requestParameters(), AutoDocumentation.description(), AutoDocumentation.methodAndPath(),
                                AutoDocumentation.section()))
                .build();
```

**Comment by fbenz** [comment]
`restdocs-api-spec` works by extracting data out of the Spring REST Docs snippets. For example, for the request fields it is done in [MockMvcRestDocumentationWrapper#122](https://github.com/ePages-de/restdocs-api-spec/blob/master/restdocs-api-spec/src/main/kotlin/com/epages/restdocs/apispec/MockMvcRestDocumentationWrapper.kt#L122).

There are two issues when trying to combine Spring Auto REST Docs and `restdocs-api-spec`:
* `restdocs-api-spec` does not know about the Spring Auto REST Docs snipptes and only those snippets contain the instrospection and Javadoc data.
* The extraction process in `restdocs-api-spec` runs before the Spring Auto REST Docs snipptes have the introspection data. So even if `restdocs-api-spec` would handle the Spring Auto REST Docs snipptes, it could not extract data at that point in time because the data is only added at a later stage.

Thus, I see no easy way of getting both extensions to work with each other.

**Comment by cnsgithub** [comment]
That's too bad. Thanks for your detailed answer anyway.

**Comment by mduesterhoeft** [comment]
A way to achieve this would be to build an extension point into `spring-auto-restdocs` that is called after the introspection is finished. Once the interface of such an extension is clear I would be happy to build an implementation of this extension point int `restdocs-api-spec`.

**Comment by jmisur** [comment]
There isn't official extension model and it would probably by some overkill without having something working on top of it. I already prototyped how a Postman collection could be exported here https://github.com/ScaCap/spring-auto-restdocs/pull/277.

In essence: 
1. Create a static ClassRule which holds the resulting collection data during the entire run of the test (= all tests to be exported in one collection/schema must run in one go). 
2. Then, for each test, run postman snippet which essentially gathers all relevant data for a particular endpoint (just like normal snippets) and flushes it in appropriate format to the shared collection.
3. At the end the ClassRule flushes all data into a file on a disk.

If it would work for you, I can cleanup and merge my PR and then you can build on top of it.

**Comment by fbenz** [comment]
Further alternatives:
* https://github.com/fbenz/restdocs-to-swagger - rather complicated and hard to automate
* We use Springfox in addition to Spring Auto REST Docs. There is no connection between both setups and the required configuration is rather small (see below). I guess that this can also help to get OpenAPI YAML.

Maven
```
        <!-- SWAGGER UI -->
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-bean-validators</artifactId>
        </dependency>
```

Config
```
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@EnableSwagger2
@Configuration
public class SwaggerConfiguration {
    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .forCodeGeneration(true)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.any())
                .build();
    }
}
```

Security (if it should be public)
```
                .antMatchers(
                        "/swagger-resources/**",
                        "/swagger-ui.html",
                        "/v2/api-docs/**"
                ).permitAll()
```
