### ISSUE TITLE
Allow for Required Title Instead of Optional

### ISSUE THREAD

**Issue by brianwyka** [ScaCap/spring-auto-restdocs#286]
Allow the user to choose whether the title in the table reads `Optional` or `Required`.  If `Required` is chosen, the logic just needs to be inverted for showing `Yes`, `No` in column value.

**Comment by brianwyka** [comment]
@jmisur I can tackle this one.  I would like to contribute if you see it as a worthwhile addition.

**Comment by brianwyka** [comment]
It seems you can use `userMessages` to customize the title, but the logic will be reversed, so need something a bit more.

**Comment by jmisur** [comment]
Hi @brianwyka, feel free to investigate and submit a PR. 
Relates to https://github.com/ScaCap/spring-auto-restdocs/issues/115.

**Comment by jmisur** [comment]
Hi, any progress in this area?

**Comment by brianwyka** [comment]
No, unfortunately I have not had time to work on this.

**Comment by jmisur** [comment]
We're not tackling this problem from our side, but feel free to submit a PR.
