### ISSUE TITLE
Allow For Multiple Request / Response Examples in Section Snippet

### ISSUE THREAD

**Issue by brianwyka** [ScaCap/spring-auto-restdocs#287]
There may be instances where it is necessary to display different scenarios of requests and responses.  This can be done currently, outside of the `SectionSnippet` but it would be nice to have in `SectionSnippet`.

The feature should allow each of the examples to be titled and have an optional description.

**Comment by jmisur** [comment]
It would be nice to have, however it's low prio since you can work around by adding unlimited snippets to your documents seamlessly, just like you described.

**Comment by jmisur** [comment]
Hi, if you submit a PR, we would definitely look at it. But currently it looks like it has a very workable solution by including any number of examples with titles in asciidoc manually and structure it any way required, because it's very flexible. So we are most likely not going to look at this.
