### ISSUE TITLE
Wrong numeric type

### ISSUE THREAD

**Issue by m-titov** [ScaCap/spring-auto-restdocs#294]
AR: Long type doc as Integer
ER: Long type doc as Long

**Comment by jmisur** [comment]
Would you might elaborating more? I'm struggling to understand the problem and desired outcome.

**Comment by m-titov** [comment]
@jmisur 
Class attribute with Long type should be documented as attribute with Long type but it documents as attribute with Integer type. I suspect it's because of this method: https://github.com/ScaCap/spring-auto-restdocs/blob/d542336625e63d197910e2aa784110d06d93a39c/spring-auto-restdocs-core/src/main/java/capital/scalable/restdocs/util/TypeUtil.java#L75 Could it be changed as:

```private static String getSimpleName(String canonicalName) {
        switch (canonicalName) {
        case "java.lang.Byte":
            return "Byte";
        case "java.lang.Short":
            return "Short";
        case "java.lang.Integer":
        case "java.math.BigInteger":
            return "Integer";
        case "java.lang.Long":
            return "Long";
        case "java.lang.Float":
        case "java.lang.Double":
        case "java.math.BigDecimal":
            return "Decimal";
        case "java.lang.Character":
        case "java.lang.String":
            return "String";
        case "java.lang.Boolean":
            return "Boolean";
        default:
            return getSpecialTypeName(canonicalName);
        }
```
?

**Comment by jmisur** [comment]
The documentation types are not meant to be 1-1 with java types. Integer and Decimal here mean "Integer number" and "Decimal number" without any relation to actual implementation. It could theoretically be just plain javascript "Number", but we think understanding if the number could be decimal or not is beneficial for consumers. To provide more details about constraints of this number to your clients, you can use JSR-303 annotations or Javadoc to be more specific.
