### ISSUE TITLE
No json files are generated when running Java 11

### ISSUE THREAD

**Issue by niknetniko** [ScaCap/spring-auto-restdocs#298]
I'm not sure if I'm missing anything, but the description (and other information extracted from Javadoc) is always empty when running on JDK 11.

This is because the json output directory is empty. For some reason, no json files are produced.

When I run the exact same thing with Java 8, using `capital.scalable:spring-auto-restdocs-json-doclet:2.0.3` instead of `capital.scalable:spring-auto-restdocs-json-doclet-jdk9:2.0.3`, the json files are produced.

(I would have liked to test the samples, but that didn't work because version 2.0.4 is not found for some reason)

Cleaned up gradle file:
```groovy
plugins {
	id 'org.asciidoctor.convert' version '1.5.3'
	id 'org.springframework.boot' version '2.1.3.RELEASE'
	id 'io.spring.dependency-management' version '1.0.7.RELEASE'
	id 'java'
}

group = 'bds'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

configurations {
	jsondoclet
}

repositories {
	mavenCentral()
	jcenter()
	maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
}

ext {
	snippetsDir = file('${buildDir}/generated-snippets')
	javadocJsonDir = file("${buildDir}/generated-javadoc-json")
}

dependencies {
	// Spring stuff
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'

	// Test stuff
	testImplementation 'org.springframework.boot:spring-boot-starter-test'

	// Docs stuff
	asciidoctor 'org.springframework.restdocs:spring-restdocs-asciidoctor'
	testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
	testImplementation 'capital.scalable:spring-auto-restdocs-core:2.0.3'
	jsondoclet 'capital.scalable:spring-auto-restdocs-json-doclet-jdk9:2.0.3'
}

task jsonDoclet(type: Javadoc, dependsOn: compileJava) {
	source = sourceSets.main.allJava
	classpath = sourceSets.main.compileClasspath
	destinationDir = javadocJsonDir
	options.docletpath = configurations.jsondoclet.files.asType(List)
	options.doclet = 'capital.scalable.restdocs.jsondoclet.ExtractDocumentationAsJsonDoclet'
	options.memberLevel = JavadocMemberLevel.PACKAGE
}

test {
	systemProperty 'org.springframework.restdocs.outputDir', snippetsDir
	systemProperty 'org.springframework.restdocs.javadocJsonDir', javadocJsonDir
	dependsOn jsonDoclet
}

asciidoctor {
	dependsOn test
}
```

**Comment by niknetniko** [comment]
I have investigated the problem and found the issue: the output is always generated in the default location, regardless of the  `-d` option. Below is a detailed overview of why this happens:

> Running a doclet with unknown options results in an error. Therefor, the jdk9 doclet rightly extends the `StandardDoclet`, and includes all of its options. However, there is no way to access the default options. Consequently, the jdk9 doclet adds its own option for `-d`. The unintended result of this is that there are now two options for `-d`, but only one will receive the actual argument. I have resolved this by extracting the existing option for `-d`, wrapping it to access the data, and replacing it.

The fix is here: https://github.com/niknetniko/spring-auto-restdocs/commit/83e1b4c4208e50c879dcee025a20387e9c42f9a2. If you are interested, I can make a pull request.

**Comment by jmisur** [comment]
Hi @niknetniko, we haven't tested java 11 yet. Of course you can submit a PR and we'll have a look. Your commit https://github.com/niknetniko/spring-auto-restdocs/commit/83e1b4c4208e50c879dcee025a20387e9c42f9a2 contains some option wrapper and it looks like a workaround. Are you sure there is no other option to get to the original `-d` option in more natural way? Your help would be appreciated.

**Comment by jmisur** [comment]
BTW 2.0.4. is on maven central.

**Comment by kret** [comment]
I am seeing same bug; 2.0.4 does not fix this.
If you want a case to reproduce or test fixes: https://github.com/kret/spring-auto-restdocs-jdk11-bug

**Comment by niknetniko** [comment]
@jmisur I know it is a workaround, but I have not found any other way. I have also not found any other doclet implementation of the new api that uses these options. Of course it is possible there is another way I have not found yet.

I'll test the workaround against @kret's case next week and if it also works, I'll make a pull request; even if only as a temporary workaround until we find a better method of doing it.

**Comment by jmisur** [comment]
Thanks we'll have a look.

**Comment by jmisur** [comment]
I tested your patch in it works nicely. 
2.0.5-SNAPSHOT latest is now on sonatype with patch and official Java 10/11 support ;)

**Comment by kret** [comment]
Could you please say if/when this is going to be released?

**Comment by jmisur** [comment]
2.0.5 was just released, it takes a couple of hours to make it to Maven central.
