### ISSUE TITLE
Hide fields in de/serialization

### ISSUE THREAD

**Issue by karlmuscat** [ScaCap/spring-auto-restdocs#309]
I have certain objects that are used in both the request and response objects. In these "common" objects, there are some fields that are not required in the request but are returned in the response. Is it possible to ignore/not show these field in the "Request Fields" and "Example request" snippets, and only show them in the "Response Fields" and "Example response" snippets?

Example: 'createdDate' field not required in request but will be returned in response. 

According to Jackson, the below produces this effect (using lombok annotations):
```
@Getter(onMethod = @__({@JsonProperty}))
@Setter(onMethod = @__({@JsonIgnore}))
private ZonedDateTime createdDate = ZonedDateTime.now();
```
However, this is not reflected in the documentation. the 'createdDate' field is documented in all 4 snippets.

**Comment by jmisur** [comment]
Sorry we did not respond. This is a broader problem with Jackson, we are using only Serializer part to determine fields, so setter customizations are ignored. 
Similar to #142.
