### ISSUE TITLE
isCollection should include Iterable

### ISSUE THREAD

**Issue by cmercer** [ScaCap/spring-auto-restdocs#316]
In AbstractJacksonFieldSnippet isCollection checks for

1.0.X
- If its a collection
- If its scala traversable

master
- if its a collection
- if its a stream
- if its scala traversable

I think collection should be changed to Iterable.  This would cover Collections but also cover cases like HATEOAS PagedResources.

**Comment by jmisur** [comment]
I know it looks a bit weird that we're not supporting generic Iterable. However there are so many implementations of Iterable that even Spring doesn't support and also some are supposed to be shown differently (e.g. Paged resources contain metadata). Therefore including such generic class would be probably cause of more bugs. If anyone needs a type to add, it's not a problem and a quick task.
