### ISSUE TITLE
Consider to change private methods of snippets (like, DescriptionSnippet) to protected

### ISSUE THREAD

**Issue by cosysoft-ru** [ScaCap/spring-auto-restdocs#330]
In my code I always try to omit method comment of a rest controller method, if I can describe all necessary information through @return and @param.
So, I'm about to extend DescriptionSnippet to change description construction (extract @return comment and concatenate "Returns " to the beginning if no method comment is found).
But, I can not simply override `capital.scalable.restdocs.misc.DescriptionSnippet#resolveComment` because of private modifier, and forced to do a lot of copy-paste.

Same goes for `capital.scalable.restdocs.section.SectionSnippet#resolveTitle` and another snippets

**Comment by jmisur** [comment]
Hi, this looks like good extension suggestion.
BTW How are you going to extract @return comments?

**Comment by jmisur** [comment]
I'm just curious because it might require some extension of our Doclet and `JavadocReader`. So maybe by making more things open we could completely enable usage of custom tags from Javadoc to Snippet. 
Is `JavadocReader#resolveMethodTag` sufficient for you to do this for `@return` comments?

**Comment by cosysoft-ru** [comment]
Hello!
> How are you going to extract @return comments?
> Is JavadocReader#resolveMethodTag sufficient for you to do this for @return comments?

Yes, I do exactly that:
```
private String resolveComment(HandlerMethod handlerMethod, JavadocReader javadocReader) {
    final Class<?> javaBaseClass = handlerMethod.getBeanType();
    final String javaMethodName = handlerMethod.getMethod().getName();
    final String methodRawReturnComment = javadocReader.resolveMethodTag(javaBaseClass, javaMethodName, "return");
...
```
