### ISSUE TITLE
"No description found for constraint" warnings increased

### ISSUE THREAD

**Issue by fbenz** [ScaCap/spring-auto-restdocs#336]
With the introduction of the following line https://github.com/ScaCap/spring-auto-restdocs/pull/317/files#diff-9f986a9a5550c5f97b02ca5e1c667f29R88 we get may more warnings like
```
WARN 5504 --- [           main] .c.ConstraintAndGroupDescriptionResolver : No description found for constraint capital.scalable.restdocs.example.items.ItemResponse: Can't find resource for bundle java.util.PropertyResourceBundle, key capital.scalable.restdocs.example.items.ItemResponse.description
```
See https://travis-ci.org/ScaCap/spring-auto-restdocs/jobs/544592362#L2367

This issue originates from a discussion on StackOverflow: https://stackoverflow.com/questions/56571805/no-description-found-for-classes-with-custom-jackson-objectmapper?noredirect=1

There are at least two things here:
* It is misleading that the warning speaks of constraints in the new cases. So is `ConstraintAndGroupDescriptionResolver` used in the right context
* I'm not convinced that the warning is helpful at all. It hints at potential setup issues but can be safely ignored in most cases. Thus, I suggest changing the log level to debug.

PR: https://github.com/ScaCap/spring-auto-restdocs/pull/335

@jmisur What are your thoughts?

**Comment by jmisur** [comment]
I believe we can silence it.
