### ISSUE TITLE
How to support scaladoc？

### ISSUE THREAD

**Issue by GeTOUO** [ScaCap/spring-auto-restdocs#339]
My project mixes Scala and java, because scala's case class is very convenient, I hope this library can support scaladoc parsing. Can this be done? Thank you

**Comment by fbenz** [comment]
The project can currently be used with two documentation processors: Javadoc doclet that is shipped with Java and Dokka that is available for Kotlin. In both cases, the documentation is converted to a custom JSON format and then consumed. I guess that neither processor works with scaladoc, but I have never looked at scaladoc. If this is true, one would have to create a tool that converts scaladoc to the JSON format that is consumed by Spring Auto REST Docs.

**Comment by GeTOUO** [comment]
Yes, I found a project to generate Javadoc for scala classes: [GenJavadoc](https://github.com/lightbend/genjavadoc). But it didn't work properly in my project.

**Comment by fbenz** [comment]
There are still no plans from our side to support Scala. However, contributions are welcome.
