### ISSUE TITLE
Constraints - custom message

### ISSUE THREAD

**Issue by mfolnovic** [ScaCap/spring-auto-restdocs#341]
It seems like overridden `message` in javax constrains are ignored, e.g. 

```@Size(min = 10, max = 500, message = "Content length must be between 10 and 500 characters long")``` 

still generates:

```Size must be between 10 and 500 inclusive.```

in snippet.

**Comment by gokhanteta** [comment]
Could you please support overridden messages in javax validation constraints?

**Comment by jmisur** [comment]
This should be fixed in the latest snapshot. If you're still interested you can give it a try.
