### ISSUE TITLE
Support for generic types on custom classes

### ISSUE THREAD

**Issue by lynings** [ScaCap/spring-auto-restdocs#347]
Hey buddy, this is a great open source framework. I have encountered some problems with this framework today, I hope you can give me some help, thank.

**Version**
```
dependencies {
    testCompile group: 'capital.scalable', name: 'spring-auto-restdocs-core', version: '2.0.5',    
    jsondoclet group: 'capital.scalable', name: 'spring-auto-restdocs-json-doclet', version: '2.0.5'
}
```
### Problem
The Rest document loses the response fields when I use a generic response object.

**API**
```
@PostMapping
public Mono<CommonIdResult<Long>> create(@RequestBody CreatePatientCommand command) {
    command.validate();
    Long id = patientAppService.registry(command);
    return Mono.just(new CommonIdResult<>(id));
}
```

**Response Object(Generic Type)**
```
@NoArgsConstructor
@Getter
public class CommonIdResult<T> {

    private T id;

    public CommonIdResult(T id) {
        this.id = id;
    }
}
```
**REST Doc(Missing response fields)**

![image](https://user-images.githubusercontent.com/14272789/63070952-c6ca9e80-bf4f-11e9-8c6f-1218d9443d1e.png)

---

**I tried to explicitly specify the data type, the generated document is really what I want, but it becomes less flexible**

---

**I tried to use flux, which solves some problems., but the generated documentation is not what I want.**

```
@PostMapping
public Flux<CommonIdResult<Long>> create(@RequestBody CreatePatientCommand command) {
    command.validate();
    Long id = patientAppService.registry(command);
    return Flux.just(new CommonIdResult<>(id));
}
```

![image](https://user-images.githubusercontent.com/14272789/63071490-0f835700-bf52-11e9-8f02-af81d70c62c8.png)

---
**I expect to be able to get such a document when I use generics**

![image](https://user-images.githubusercontent.com/14272789/63071627-9fc19c00-bf52-11e9-9d9d-69e769f0001b.png)

**Comment by jmisur** [comment]
Hi, unfortunately we don't support arbitrary generic types on custom classes. The only generics we support is on well known spring classes so far.

**Comment by lynings** [comment]
> Hi, unfortunately we don't support arbitrary generic types on custom classes. The only generics we support is on well known spring classes so far.

Okay, thank you for your answer.

**Comment by qinkangdeid** [comment]
> Hi, unfortunately we don't support arbitrary generic types on custom classes. The only generics we support is on well known spring classes so far.

are there plans to support it?

**Comment by jmisur** [comment]
We did not hit this problem so far, but we can have a quick look.
Since we receive information about classes themselves from Jackson serialiser, we depend on what it can deliver.

**Comment by jmisur** [comment]
Support for Spring WebFlux was added in 2.0.2. If there are any issues with it, pleae open a new specific ticket.
