### ISSUE TITLE
How to document same method twice, e.g. to document error conditions?

### ISSUE THREAD

**Issue by atrifyllis** [ScaCap/spring-auto-restdocs#352]
For example, if I test same method twice the description is the same for both tests which does not make much sense for the reader of the documentation

**Comment by jmisur** [comment]
Just customize your asciidoc file where you import all snippets.
You can extend any section with custom followup snippets like this:
```
include::{snippets}/account/bank/deposit/post/auto-section.adoc[]
==== Example request/response with validation errors
include::{snippets}/account/bank/deposit/post_error/curl-request.adoc[]
include::{snippets}/account/bank/deposit/post_error/http-response.adoc[]
```
Where `account/bank/deposit/post` is your main documentation section and `account/bank/deposit/post_error` are error scenarios (import only relevant subsections like curl-request and http-response).

**Comment by atrifyllis** [comment]
@jmisur Thank you! 

This is what I thought of doing, just wanted to confirm that this is the "right" way

**Comment by jmisur** [comment]
You're welcome ;)
