### ISSUE TITLE
How to customize query object to generate query parameters snippet

### ISSUE THREAD

**Issue by lynings** [ScaCap/spring-auto-restdocs#355]
```
asciidoctor 'org.springframework.restdocs:spring-restdocs-asciidoctor:2.0.3.RELEASE'
jsondoclet group: 'capital.scalable', name: 'spring-auto-restdocs-json-doclet', version: '2.0.5'
```

```
@GetMapping
public Mono findByPage(@ModelAttribute final FindPatientByPageQuery query) {
    .....
}


@Setter
@Getter
public class FindPatientByPageQuery extends Page {

    private String name;

    private String phoneNumber;

    .....
}
```
Hey guys, I had a problem using spring-auto-restdocs.

When I add @ModelAttribute to FindPatientByPageQuery object, the location of parameter generation is request field snippet rather than query parameters snippet.

When I did not add @ModelAttribute, API doc did not generate query parameters snippet and request fields snippet.

I expect the FindPatientByPageQuery object requested by GET to generate query parameters snippet. How can I solve this problem?

**Comment by jmisur** [comment]
Hi, ModelAttribute is very universal approach of mapping query or form parameters into a single object. It also supports mapping of some local attributes independent of the request itself (model prepopulation). So it's very hard for us to determine where this and that parameter is supposed to come from. Therefore we currently don't support it.

**Comment by lynings** [comment]
> Hi, ModelAttribute is very universal approach of mapping query or form parameters into a single object. It also supports mapping of some local attributes independent of the request itself (model prepopulation). So it's very hard for us to determine where this and that parameter is supposed to come from. Therefore we currently don't support it.

Thank you for your answer, **How can I generate request parameters snippet if I don't use ```@ModelAttribute``` ？**

Because don't use ```@ModelAttribute```, query parameters snippet and request fields snippet are empty.

**For example:**

```java
@GetMapping
public Mono findByPage(FindPatientByPageQuery query) {
    .....
}

@Setter
@Getter
public class FindPatientByPageQuery extends Page {
    private String name;
    private String phoneNumber;
    .....
}
```

![image](https://user-images.githubusercontent.com/14272789/66253159-51808a80-e796-11e9-8c4f-9e430e35bd96.png)

---

If use ```@ModelAttribute```, query parameters snippet will be empty，but request fields snippet will not empty.

**For example:**

```java
@GetMapping
public Mono findByPage(@ModelAttribute FindPatientByPageQuery query) {
    .....
}


@Setter
@Getter
public class FindPatientByPageQuery extends Page {
    private String name;
    private String phoneNumber;
    .....
}
```

![image](https://user-images.githubusercontent.com/14272789/66252959-10877680-e794-11e9-884c-745aaa6d9496.png)

So I got a less accurate document because the request field is the request body in HTTP.

---

If use ```@RequestParam``` can generate query parameters snippet, but it becomes especially inflexible when there are more parameters.

**Comment by jmisur** [comment]
You really need to use `@RequestParam` for query parameters, there is no way around it currently.
If you want to include paging support, you don't need to include it explicitly - see [documentation](https://scacap.github.io/spring-auto-restdocs/#paging) and [example project](https://htmlpreview.github.io/?https://github.com/ScaCap/spring-auto-restdocs/blob/master/samples/java-webmvc/generated-docs/index.html) and [code](https://github.com/ScaCap/spring-auto-restdocs/blob/121e16caf8484955275b8f14dfa0eb0a1c6d9f05/samples/java-webmvc/src/main/java/capital/scalable/restdocs/example/items/ItemResource.java#L200).

**Comment by lynings** [comment]
> You really need to use `@RequestParam` for query parameters, there is no way around it currently.
> If you want to include paging support, you don't need to include it explicitly - see [documentation](https://scacap.github.io/spring-auto-restdocs/#paging) and [example project](https://htmlpreview.github.io/?https://github.com/ScaCap/spring-auto-restdocs/blob/master/samples/java-webmvc/generated-docs/index.html) and [code](https://github.com/ScaCap/spring-auto-restdocs/blob/121e16caf8484955275b8f14dfa0eb0a1c6d9f05/samples/java-webmvc/src/main/java/capital/scalable/restdocs/example/items/ItemResource.java#L200).

Although there is no good way to solve this problem at present, thank you very much.

**Comment by AnWeber** [comment]
@lynings why not implement a custom snippet. please view files in my test project: [JacksonRequestParametersSnippet.java](https://github.com/AnWeber/springrestdocs/blob/master/src/test/java/de/bpmn/springrestdocs/web/JacksonRequestParametersSnippet.java) and used by [TaskControllerTest.java](https://github.com/AnWeber/springrestdocs/blob/master/src/test/java/de/bpmn/springrestdocs/web/TaskControllerTest.java)

@jmisur I think the current implementation of the ModelAttribute Annotation (#95) is not ideal and could be improved. If the [RequestMethod](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/bind/annotation/RequestMethod.html) of the HandlerMethod is not type get the current implementation is fine. But on RequestMethod.GET a request parameters section should be generated. And according to [spring docs](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-ann-modelattrib-method-args) the modelattribute annotation is optional, if no ArgumentResolver supports the type and is not of type [BeanUtils#isSimpleProperty](https://docs.spring.io/spring-framework/docs/5.2.2.RELEASE/javadoc-api/org/springframework/beans/BeanUtils.html#isSimpleProperty-java.lang.Class-). I would like to improve both features. Should I create a new issue or is such a change not desired? I could provide a pull request, if needed.

**Comment by jmisur** [comment]
@AnWeber pull request would be great, as I'm not sure about the cases you described.
The error you get from the build is due to missing test jar (it's not published by Spring guys). Please follow [Contribution](https://scacap.github.io/spring-auto-restdocs/#contributing-installing-testjar) steps to make it work locally.

**Comment by AnWeber** [comment]
@jmisur thanks for your hint to the contribution guidelines. Now I can compile the code, but license-maven-plugin automatically updates hundred of files (2020). I would prefer, if I do not contribute these changes.

**Comment by lynings** [comment]
> @lynings why not implement a custom snippet. please view files in my test project: [JacksonRequestParametersSnippet.java](https://github.com/AnWeber/springrestdocs/blob/master/src/test/java/de/bpmn/springrestdocs/web/JacksonRequestParametersSnippet.java) and used by [TaskControllerTest.java](https://github.com/AnWeber/springrestdocs/blob/master/src/test/java/de/bpmn/springrestdocs/web/TaskControllerTest.java)
> 
> @jmisur I think the current implementation of the ModelAttribute Annotation (#95) is not ideal and could be improved. If the [RequestMethod](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/bind/annotation/RequestMethod.html) of the HandlerMethod is not type get, the current implementation is fine. But on RequestMethod.GET a request parameters section should be generated. And according to [spring docs](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-ann-modelattrib-method-args) the modelattribute annotation is optional, if no ArgumentResolver supports the type and is not of type [BeanUtils#isSimpleProperty](https://docs.spring.io/spring-framework/docs/5.2.2.RELEASE/javadoc-api/org/springframework/beans/BeanUtils.html#isSimpleProperty-java.lang.Class-). I would like to improve both features. Should I create a new issue or is such a change not desired? ~I could provide a pull request, if needed.~ I could not provide a pull request. Current version does not compile on my machine, because of missing dependency (=>
> [error.txt](https://github.com/ScaCap/spring-auto-restdocs/files/4021838/error.txt))

Fantastic!
I fork your repository and built the project, the API documentation looks more friendly than before.Buddy you are great!

**Comment by fbenz** [comment]
Perfect. There will be a release that includes the feature soon.

**Comment by AnWeber** [comment]
Thanks

Florian Benz <notifications@github.com> schrieb am So., 9. Feb. 2020, 09:44:
