### ISSUE TITLE
How to document an object coming from an external lib?

### ISSUE THREAD

**Issue by JeremieLapert** [ScaCap/spring-auto-restdocs#361]
Hello,
I can find how document an object coming from an external lib, which is the @RequestBody parameter of my controller. 
This isn't possible ? it's an issue ? Or I do not know how to search?

this is my Controller that i wany document and the SalesVolume come from external lib : 
`fun getSalesVolumes(@RequestBody salesVolume: SalesVolume): ResponseEntity<BigDecimal> {}`

**Comment by jmisur** [comment]
Hi, please take a look into our [samples](https://github.com/ScaCap/spring-auto-restdocs/blob/master/samples/). We have a shared model which is imported into examples and it works well. The only thing you need to do is to generate and attach javadoc-json when building the external model. Look at maven-javadoc-plugin in [this pom](https://github.com/ScaCap/spring-auto-restdocs/blob/master/samples/shared/pom.xml).

**Comment by JeremieLapert** [comment]
Hello, thank you for your answer, it's perfect!
