### ISSUE TITLE
Deadlock with Spring Boot 2.2.1 and lazy-initialization

### ISSUE THREAD

**Issue by hdohlmann** [ScaCap/spring-auto-restdocs#366]
Spring boot version: 2.2.1
Wire in a Repository in the autorestdoc test.
Set property spring.main.lazy-initialization=true

Deadlock in org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.getNativeEntityManagerFactory()

**Comment by jmisur** [comment]
Hi @hdohlmann can you please provide test project or some more logs/configuration? It's hard to get to the problem from your brief description. Thanks

**Comment by hdohlmann** [comment]
Sorry. Can't do that. I no longer work for the company.
Further, I found other services deadlocking during startup when lazy-initialization=true, so it probably isn't spring-auto-restdocs that is the culprit.
Feel free to close this one and sorry for the noise.

**Comment by fbenz** [comment]
Thank you for the update.
