### ISSUE TITLE
[Question] type data in spring-auto-restdocs-dokka-json

### ISSUE THREAD

**Issue by edwinRNDR** [ScaCap/spring-auto-restdocs#388]
I see you are working on a [json format extension for Dokka](https://github.com/ScaCap/spring-auto-restdocs/tree/master/spring-auto-restdocs-dokka-json), which I think is an incredibly valuable tool for anyone who wants to generate documentation but does not quite feel like dealing with Dokka's internals. 

The output json files in `testdata` seem to only contain the javadoc/kdoc data. Are there any plans for adding Java/Kotlin type data there as well?

**Comment by fbenz** [comment]
There are no plans to go beyond Javado/KDoc. The sole purpose of the Dokka extension is to extract documentation for Spring Auto REST Docs.

Feel free to fork the Dokka extension and extend it in any way you like.
