### ISSUE TITLE
Suspected concurrent access to jdk.javadoc.doclet API

### ISSUE THREAD

**Issue by pavelrappo** [ScaCap/spring-auto-restdocs#391]
Manifests as `java.lang.IllegalArgumentException: Invalid index` and `java.lang.StringIndexOutOfBoundsException`. For more details, see
https://bugs.openjdk.java.net/browse/JDK-8214772?focusedCommentId=14338379&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14338379

**Comment by jmisur** [comment]
Hi which version do you use? This was already fixed in 2.0.4 (#289).

**Comment by pavelrappo** [comment]
You are right, I missed that change. Sorry for the noise.
