### ISSUE TITLE
Ommit wrapper class in response fields

### ISSUE THREAD

**Issue by dekar91** [ScaCap/spring-auto-restdocs#414]
Hi!
Let assume we use JSON:API implementation _JsonResponse<DTO>_ for response. Response will look like:
```
{
data: {
   // DTO fields
},
erros: [],
meta: {}
}
```
In such case fields _data_, _errors_ and _meta_ will be included into snipped, but actually describle JSON:API contract separatly.
Is there a way include only *generic* class into snipped?

**Comment by jmisur** [comment]
Hi @dekar91,
we currently don't support JSON:API or similar specs. All response entities are taken at face value as custom response types of the project. Feel free to raise a PR for JSON:API.
