### ISSUE TITLE
Kotlin not nullable with default info marked as Optional False

### ISSUE THREAD

**Issue by Athas1980** [ScaCap/spring-auto-restdocs#416]
Hi Consider the following data class

```
data class Person(val firstName:String, val lastName:String = "")
```
The lastName field will be marked as required in the documentation, even though the value will actually be the empty String.

I've looked at some classes and it appears that its set like this due to jacksons marking as as required.

**Comment by jmisur** [comment]
Please try this config and let us know if it works https://github.com/FasterXML/jackson-module-kotlin/issues/130#issuecomment-546625625

**Comment by Athas1980** [comment]
Sorry I didn't get around to testing this. At the moment I've made all my fields nullable to work around this.

**Comment by jenarros-sn** [comment]
I had the same issue and using the `nullisSameAsDefault = true` setting works.

**Comment by jmisur** [comment]
Let's reopen if more people hit this.
