### ISSUE TITLE
Does it make sense to extract the Javadoc extracting Doclet into a separate project?

### ISSUE THREAD

**Issue by odrotbohm** [ScaCap/spring-auto-restdocs#435]
There are quite a few other projects that would benefit from having the Javadoc information for classes and methods available at build time for inclusion in some Asciidoctor files. I.e. it would be cool if there was a Doclet usable standalone (the current one apparently actually is but it might feel weird to refer to a Doclet specific to REST and RESTDocs in particular for general purposes) *and* an API to access the extracted content ideally already applying Asciidoctor specific transformations. For the latter, I think most of what's needed is already available in `capital.scalable.restdocs.javadoc`.

**Comment by jmisur** [comment]
Hi Oliver, that is an interesting idea. I don't know about any other project now which could use this, but I can imagine there is a potential. 
This would however require some additional work in order to make the json data structure or some kind of API more solid/flexible. So an example would help here.

**Comment by odrotbohm** [comment]
For [Moduliths](https://github.com/odrotbohm/moduliths), we produce Asciidoctor snippets to document interesting parts of Spring applications. See [this ticket](https://github.com/odrotbohm/moduliths/issues/143) for details. The corresponding [commit](https://github.com/odrotbohm/moduliths/commit/3740df8c8ae5cf309e5af1bab728b84a43a90229) introduces [an abstraction](https://github.com/odrotbohm/moduliths/commit/3740df8c8ae5cf309e5af1bab728b84a43a90229#diff-47d864f13c55278fc5df6c19fe02afcbc89f325cb753b97aa666f53a6a5ec5abR28-R37) to obtain documentation for a method and [a Spring Auto RESTDocs based implementation](https://github.com/odrotbohm/moduliths/commit/3740df8c8ae5cf309e5af1bab728b84a43a90229#diff-faff01c014feb62b5cb6c6d06d002a138466cd2f9a9cd254b3ee8243f732379dR31-R44) that uses the metadata generated by the doclet.

The weird thing about the arrangement is that I now have to include a dependency that deals with REST API documentation on a project that potentially doesn't even expose an API just to be able to generate documentation for Spring internal event listeners. While inconvenient it's also not a big problem for now. #434 slightly plays into this as well as the methods to be documented often use the same name and only differ in the method parameter.
