### ISSUE TITLE
Supports for Spring Webflux Functional Endpoint

### ISSUE THREAD

**Issue by japharr** [ScaCap/spring-auto-restdocs#436]
Hello guys, I have been having some challenges trying to implement this library with Spring Webflux using Functional Endpoints. Does this great library support Spring Webflux with Functional Endpoint instead of annotation controller?

Thanks.

**Comment by jmisur** [comment]
Hi Jelil, we currently don't support functional endpoints. That would need most likely a completely new implementation and I don't think Spring REST Docs support either.
