### ISSUE TITLE
Gradle 7/Kotlin 1.5 support

### ISSUE THREAD

**Issue by fhoner** [ScaCap/spring-auto-restdocs#450]
Hi, is there any plan to support Kotlin 1.5 and Gradle 7 respectively? I've tried to upgrade our project and faced issues at spring-auto-restdocs. As I understood, it would either be necessary to provide some kind of a backport fix for dokka 0.10.1, or migrate spring-auto-restdocs to use the rewritten dokka >=1.4. In the latter case, the json generating approach would be different, as dokka moved to a plugin architecture.

**Comment by iuliandavid** [comment]
It would be a nice feature to provide a backport fix for dokka 0.10.1.

**Comment by jmisur** [comment]
Hi all, we'll look into it but cannot ensure any timelines. A PR with upgrades of dokka extension are welcome.

**Comment by JeremieLapert** [comment]
hello, still no progress on this subject?

**Comment by combineads** [comment]
Hi. What are the problems?
Will the problem be solved if only Dokka is upgraded?
@jmisur @iuliandavid

**Comment by fbenz** [comment]
I started looking into migrating to the latest Dokka version. The whole integration change and thus it's a rewrite for our plugin. However, I can't provide a timeline.

**Comment by JeremieLapert** [comment]
@fbenz : thanks for thank you for your feedback, good luck and we stay tuned for news from you.
