### ISSUE TITLE
Please support jpms

### ISSUE THREAD

**Issue by originalrusyn** [ScaCap/spring-auto-restdocs#471]
It looks impossible to use your lib in jpms (Java Platform Module System ) modular app because of next error:

`error: module custom.module reads package capital.scalable.restdocs.jackson from both spring.auto.restdocs.core and spring.auto.restdocs.annotations`

Could you please fix it?

**Comment by fbenz** [comment]
There are currently no plans to support JPMS as there are more important topics still in the pipeline and I'm the sole maintainer at the moment. However, an external contribution is welcome.

**Comment by originalrusyn** [comment]
@fbenz 
JPMS throws the error because the same java package `capital.scalable.restdocs.jackson` is used in different jar.
So, it should be easily fixed by just to renaming the java package in one of jar or by union all files of both jar into single jar.
