### ISSUE TITLE
Spring Boot 3.x and Jakarta Validation API - RequestBody fields annotated with @NotNull are Optional true in generated documentation

### ISSUE THREAD

**Issue by anamariasmith** [ScaCap/spring-auto-restdocs#473]
Dear ScaCap team,

I want to use spring-auto-restdocs with following versions
spring-restdocs-mockmvc.version 3.0.0
spring-boot 3.0.6
spring-auto-rest-docs-core.version 2.0.11
and there is a problem in generated documentation that all fields from RequestBody which are annotated with @NotNull are marked as Optional true in the documentation (they should be Optional false). I am not sure if this is something related with SpringBoot 3.x and Jakarta Validation API or it is something else.
Could you please take a look into this issue. Please let me know if more details are needed from my side.

Thank you very much in advance and thank you very much for your great work.

**Comment by anamariasmith** [comment]
Dear ScaCap team,

Is there any update on this issue?

Best regards.

**Comment by fbenz** [comment]
I'm sorry but there are no plans to support Spring Boot 3 right now. The project isn't actively maintained at the moment.
