### ISSUE TITLE
Do you have plans to support the OpenAPI Specification project.?

### ISSUE THREAD

**Issue by bnjjong** [ScaCap/spring-auto-restdocs#475]
First of all, I'm an avid user of Spring Auto REST Docs. As mentioned in the title, I've been exploring ways to transition from Restdocs to support the adoption of the OpenAPI Specification. I'm working on an open-source project, and the link is attached below.
[link](https://github.com/ePages-de/restdocs-api-spec)

However, the problem is that when trying to apply it in the Auto REST Docs environment, it seems to work, but the API specification is not getting written at all. With the mainstream adoption of Microservices Architecture (MSA) and eventually needing to use OAS, it seems inevitable. However, Spring Auto REST Docs is too convenient to let go, and if there's any plan in the pipeline, I'd love to contribute! Please share your feedback.

**Comment by fbenz** [comment]
There are no plans from our side and we actually stopped maintaining Spring Auto REST Docs, see https://github.com/ScaCap/spring-auto-restdocs#end-of-life-notice
We also valued the convenience and played with automatic conversions but eventually dropped Spring (Auto) REST Docs completely.
