### ISSUE TITLE
Compatibility with Gradle

### ISSUE THREAD

**Issue by JanPflugmacher** [ScaCap/spring-auto-restdocs#56]
There is an issue with the Doclet and how that Doclet and JavaDoc are called from within Gradle.

From my research is understand that Gradle is passing default values from various flags. One of those flags if for example the `"-d"` flag. 

Due to the Doclet and it not supporting those flags that Gradle passes the build process always fails with the following error. It may possible that there are other flags that have to be checked as well.

`javadoc: error - invalid flag: -d`

I would appreciate a fix for the doclet.

**Comment by jmisur** [comment]
Hi Jan, thanks for the report and quick analysis, we'll work on Gradle support in the near future. The Doclet part might have quick fix on our side, hopefully it's the only obstacle.

**Comment by jmisur** [comment]
Hi Jan, we just released 1.0.5 which should work with Gradle now. Our example project can be built with Gradle, check out https://github.com/ScaCap/spring-auto-restdocs/tree/master/spring-auto-restdocs-example. Pls let us know if it works for you.

**Comment by JanPflugmacher** [comment]
Thank you for the quick fix.
As far as I can tell it works perfectly fine for me.
