### ISSUE TITLE
Support for generic types for response object

### ISSUE THREAD

**Issue by itERRatOR** [ScaCap/spring-auto-restdocs#88]
When I use explicit types extending generic types for `@ResponseBody`, only fields from parent generic types are discovered and added to a response documentation, specific type fields are not picked up.
Is it me doing something wrong, or there is no support for generic types in general so far?
Thanks!

**Comment by itERRatOR** [comment]
Ok, I can see the pattern now. There is support for generic types. But fields that are used in `@JsonCreator` and/or annotated as '@JsonProperty' in constructor are not picked up for some reason.

**Comment by fbenz** [comment]
Thank you for reporting and digging into it. Can you please provide a small example that helps us identifying why this case is not handled as expected?

**Comment by itERRatOR** [comment]
I found out how to fix the issue I was facing. When using `@JsonCreator` I also have to mark all calss members that I want to appear in the documentation as `@JsonProperty`. I am not sure why it is required but it works for me. I will also provide a modified example of `ItemResponse` based on your sample application later on here (as I don't have access to that source code right now).

**Comment by jmisur** [comment]
Seems it's working for you now.
