### ISSUE TITLE
Doesn't generate doc for GET request params mapped with @ModelAttribute anno.

### ISSUE THREAD

**Issue by m-titov** [ScaCap/spring-auto-restdocs#95]
Subj. Example of code:
@GetMapping("/classes")
    List<SearchClassesResponse> searchClasses(@Validated @ModelAttribute SearchClassesRequest searchClassesRequest)  {
        return groupXClassBriefService.searchClasses(searchClassesRequest);
    }
Please help.

**Comment by fbenz** [comment]
Thank you for opening the issue. `@ModelAttribute` is not supported yet and a bit tricky. So far we only support POJO JSON conversion with Jackson. In the case of `@ModelAttribute` the input usually comes from form encoded data. In addition, fields of the model might not even come from the request, but are set in other parts of the code. Therefore, I'm not sure whether we want support this case. But we are happy for any input and ideas. Anyway, you can always document such an endpoint with Spring REST Docs itself.

**Comment by jmisur** [comment]
Hi @m-titov, maybe we could help with current #103. This PR allows to set request type explicitly in the test, if the restdocs system cannot recognise the type automatically, which is the case with `@ModelAttribute`. As Florian noted, the model might receive values from different sources as described [here](http://docs.spring.io/spring/docs/3.1.x/spring-framework-reference/html/mvc.html#mvc-ann-modelattrib-method-args), so we're really not comfortable to implement it only for one use case. 
This explicit setting of type allows you to also put in a custom type (might not be the one in the method signature), if your model receives custom values from internal sources and you don't want to publish them in the docs (such as session attributes). In this way you can construct custom 'docs only' class which imitates the request. The class can even be a superclass of the real model, so no duplication would occur.

**Comment by fbenz** [comment]
With #103 that is included in the 1.0.8 release from today we detect `@ModelAttribute` annotations as request bodies. The same PR also allows to explicitly set the type if the type of the parameter does not match the actual form fields. We didn't solve the general issue that requests for `@ModelAttribute`  controller methods are form urlencoded and we document them as JSON request. If there are no nested objects, the result should be as desired or close to it. We hope that this helps you.

**Comment by m-titov** [comment]
Thanks a lot.
