### ISSUE TITLE
Support for Rest Assured

### ISSUE THREAD

**Issue by sudr** [ScaCap/spring-auto-restdocs#96]
This is to track work towards supporting Rest Assured. Pointers to how to get started with this will be helpful.

**Comment by fbenz** [comment]
Thank you for opening the issue. It has been on our TODO list for a while. We can not provide any pointers yet, but plan to take a look in the next few days to see how much work it is and where to start.

**Comment by fbenz** [comment]
In a MockMVC test, the entry point for the introspection is the [HandlerMethod](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/method/HandlerMethod.html). We get the HandlerMethod instance with the following steps:
1. [JacksonResultHandler](https://github.com/ScaCap/spring-auto-restdocs/blob/master/spring-auto-restdocs-core/src/main/java/capital/scalable/restdocs/jackson/JacksonResultHandlers.java#L34) is registered as a MockMVC ResultHandler:
https://github.com/ScaCap/spring-auto-restdocs/blob/master/spring-auto-restdocs-example/src/test/java/capital/scalable/restdocs/example/testsupport/MockMvcBase.java#L108
2. HandlerMethod instance is retrieved from MvcResult: https://github.com/ScaCap/spring-auto-restdocs/blob/master/spring-auto-restdocs-core/src/main/java/capital/scalable/restdocs/jackson/JacksonResultHandlers.java#L48
3. The HandlerMethod instance is used as an entry point for introspection: https://github.com/ScaCap/spring-auto-restdocs/blob/master/spring-auto-restdocs-core/src/main/java/capital/scalable/restdocs/snippet/StandardTableSnippet.java#L47

When using Rest Assured, one only gets information about the HTTP request and response and no additional information about the MVC method. This information can be retrieved via a filter: https://github.com/rest-assured/rest-assured/blob/master/rest-assured/src/main/java/io/restassured/filter/Filter.java#L44
and the following information can be retrived from the request:
https://github.com/rest-assured/rest-assured/blob/master/rest-assured/src/main/java/io/restassured/specification/FilterableRequestSpecification.java
Example a Spring REST Docs test with Rest Assured: https://github.com/spring-projects/spring-restdocs/blob/master/samples/rest-assured/src/test/java/com/example/restassured/SampleRestAssuredApplicationTests.java

So the question is on how to get to the HandlerMethod instance that is tested. An inconvenient option is to add a manual pointer to each test.

**Comment by jmisur** [comment]
idle issue, closing.
